# a11y-profile-manager-indicator
# Autogenerated from man page /usr/share/man/man1/a11y-profile-manager-indicator.1.gz
# using Deroffing man parser
complete -c a11y-profile-manager-indicator -s h -l help --description 'Show summary of options.'
complete -c a11y-profile-manager-indicator -l display --description 'X display to use AUTHOR A11y-profile-manager-in… [See Man Page]'

