# aarch64-linux-gnu-gcc-ar-5
# Autogenerated from man page /usr/share/man/man1/aarch64-linux-gnu-gcc-ar-5.1.gz
# using Deroffing man parser
complete -c aarch64-linux-gnu-gcc-ar-5 -l plugin --description '.'

