# apbs
# Autogenerated from man page /usr/share/man/man1/apbs.1.gz
# using Deroffing man parser
complete -c apbs -l output-file --description 'Enables output logging to the path listed in <name>.'
complete -c apbs -l output-format --description 'Specifies format for logging.'
complete -c apbs -l help --description 'Display this help information.'
complete -c apbs -l version --description 'Display the current apbs version.  EXAMPLES apbs apbs.'

