# ard-reset-arduino
# Autogenerated from man page /usr/share/man/man1/ard-reset-arduino.1.gz
# using Deroffing man parser
complete -c ard-reset-arduino -l verbose --description 'Watch what\'s going on on STDERR.'
complete -c ard-reset-arduino -l period --description 'Specify the DTR pulse width in seconds.'
complete -c ard-reset-arduino -l caterina --description 'Reset a Leonardo, Micro, Robot, LilyPadUSB or s… [See Man Page]'

