# arm-none-eabi-ar
# Autogenerated from man page /usr/share/man/man1/arm-none-eabi-ar.1.gz
# using Type1
complete -c arm-none-eabi-ar -l help --description 'Displays the list of command line options suppo… [See Man Page]'
complete -c arm-none-eabi-ar -l version --description 'Displays the version information of ar and then exits.'

