# arm-linux-gnueabi-gcc-ar
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-gcc-ar.1.gz
# using Deroffing man parser
complete -c arm-linux-gnueabi-gcc-ar -l plugin --description '.'

