# arm-linux-gnueabi-ar
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-ar.1.gz
# using Type1
complete -c arm-linux-gnueabi-ar -l help --description 'Displays the list of command line options suppo… [See Man Page]'
complete -c arm-linux-gnueabi-ar -l version --description 'Displays the version information of ar and then exits.'

