# arm-linux-gnueabi-gcc-ar-5
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-gcc-ar-5.1.gz
# using Deroffing man parser
complete -c arm-linux-gnueabi-gcc-ar-5 -l plugin --description '.'

