# arm-linux-gnueabi-dwp
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-dwp.1.gz
# using Deroffing man parser
complete -c arm-linux-gnueabi-dwp -s h -l help --description 'Print this help message.'
complete -c arm-linux-gnueabi-dwp -s e -l exec --description 'Get list of dwo files from EXE (defaults output to EXE. dwp).'
complete -c arm-linux-gnueabi-dwp -s o -l output --description 'Set output dwp file name.'
complete -c arm-linux-gnueabi-dwp -s v -l verbose --description 'Verbose output.'
complete -c arm-linux-gnueabi-dwp -l verify-only --description 'Verify output file against exec file.'
complete -c arm-linux-gnueabi-dwp -s V -l version --description 'Print version number REPORTING BUGS Report bugs to <http://www.'

