# arm-linux-gnueabi-gcc-nm
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-gcc-nm.1.gz
# using Deroffing man parser
complete -c arm-linux-gnueabi-gcc-nm -l plugin --description '.'

