# arm-linux-gnueabi-gcc-ranlib
# Autogenerated from man page /usr/share/man/man1/arm-linux-gnueabi-gcc-ranlib.1.gz
# using Deroffing man parser
complete -c arm-linux-gnueabi-gcc-ranlib -l plugin --description '.'

