# auth-client-config
# Autogenerated from man page /usr/share/man/man8/auth-client-config.8.gz
# using Type1
complete -c auth-client-config -l version --description 'show program\'s version number and exit.'
complete -c auth-client-config -s h -l help --description 'show this help message and exit.'
complete -c auth-client-config -s a -l all-types --description 'apply all types for specified profile.'
complete -c auth-client-config -s d -l database-only --description 'update file(s) only if current entries are in database.'
complete -c auth-client-config -s f -l file --description 'update FILE instead of default.'
complete -c auth-client-config -s l -l list-profiles --description 'list available profiles.'
complete -c auth-client-config -s L -l list-types --description 'list available types.'
complete -c auth-client-config -s n -l dry-run --description 'don\'t modify anything, just show the changes.'
complete -c auth-client-config -s p -l profile --description 'use PROFILE.'
complete -c auth-client-config -s r -l reset --description 'reset file(s) to previous non-auth-client-config values.'
complete -c auth-client-config -s s -l check-system --description 'determine if system files are set to PROFILE.'
complete -c auth-client-config -s S -l show-system --description 'show current system settings as a profile.'

