# avr-run
# Autogenerated from man page /usr/share/man/man1/avr-run.1.gz
# using Deroffing man parser
complete -c avr-run -s v --description 'Verbose output.'
complete -c avr-run -s t --description '" `trace\', calls a sim_trace routine that does nothing.'
complete -c avr-run -s p --description 'Generate profile information (for use with  gprof\\c ).'
complete -c avr-run -s m --description 'Set the memory size for the emulated machine to… [See Man Page]'
complete -c avr-run -l sysroot --description 'Prepend filepath to all simulator system calls … [See Man Page]'

