# avr-ar
# Autogenerated from man page /usr/share/man/man1/avr-ar.1.gz
# using Type1
complete -c avr-ar -l help --description 'Displays the list of command line options suppo… [See Man Page]'
complete -c avr-ar -l version --description 'Displays the version information of ar and then exits.'

