# avr-gasp
# Autogenerated from man page /usr/share/man/man1/avr-gasp.1.gz
# using Deroffing man parser
complete -c avr-gasp -l alternate --description 'Use alternative macro syntax.'
complete -c avr-gasp -l commentchar --description 'Use CHAR as the comment character.'
complete -c avr-gasp -l debug --description 'Show debugging statistics.'
complete -c avr-gasp -l help --description 'Display a summary of the GASP command line options.'
complete -c avr-gasp -l mri --description 'Use MRI compatibility mode.'
complete -c avr-gasp -l output --description '`-o OUTFILE\' `--output OUTFILE\' Write the outpu… [See Man Page]'
complete -c avr-gasp -l print --description 'Print line numbers.'
complete -c avr-gasp -l copysource --description 'Copy the source lines to the output file.'
complete -c avr-gasp -l unreasonable --description 'Bypass "unreasonable expansion" limit.'
complete -c avr-gasp -l version --description 'Display the GASP version number.'
complete -c avr-gasp -s a --description '.'
complete -c avr-gasp -s c --description '.'
complete -c avr-gasp -s d --description '.'
complete -c avr-gasp -s h --description '.'
complete -c avr-gasp -s M --description '.'
complete -c avr-gasp -s o --description '.'
complete -c avr-gasp -s p --description '.'
complete -c avr-gasp -s s --description '.'
complete -c avr-gasp -s u --description '.'
complete -c avr-gasp -s v --description '.'

