# avrdude
# Autogenerated from man page /usr/share/man/man1/avrdude.1.gz
# using Darwin man parser
complete -c avrdude -s p --description 'This is the only option that is mandatory for e… [See Man Page]'
complete -c avrdude -s b --description 'Override the RS-232 connection baud rate specif… [See Man Page]'
complete -c avrdude -s B --description 'Specify the bit clock period for the JTAG inter… [See Man Page]'
complete -c avrdude -s c --description 'Use the programmer specified by the argument.'
complete -c avrdude -s C --description 'Use the specified config file to load configuration data.'
complete -c avrdude -s D --description 'Disable auto erase for flash.'
complete -c avrdude -s e --description 'Causes a chip erase to be executed.'
complete -c avrdude -s F --description 'Normally, avrdude tries to verify that the devi… [See Man Page]'
complete -c avrdude -s i --description 'For bitbang-type programmers, delay for approxi… [See Man Page]'
complete -c avrdude -s l --description 'Use logfile rather than stderr for diagnostics output.'
complete -c avrdude -s n --description 'No-write - disables actually writing data to th… [See Man Page]'
complete -c avrdude -s O --description 'Perform a RC oscillator run-time calibration ac… [See Man Page]'
complete -c avrdude -s P --description 'Use port to identify the device to which the pr… [See Man Page]'
complete -c avrdude -s q --description 'Disable (or quell) output of the progress bar w… [See Man Page]'
complete -c avrdude -s s --description 'Disable safemode prompting.'
complete -c avrdude -s t --description 'Tells avrdude to enter the interactive ``termin… [See Man Page]'
complete -c avrdude -s u --description 'Disable the safemode fuse bit checks.'
complete -c avrdude -s v --description 'Enable verbose output.'
complete -c avrdude -s V --description 'Disable automatic verify check when uploading data.'
complete -c avrdude -s x --description 'Pass extended_param to the chosen programmer im… [See Man Page]'

