# axohelp
# Autogenerated from man page /Library/TeX/texbin/man/man1/axohelp.1
complete -c axohelp -s h -l help --description 'Gives usage information.'
complete -c axohelp -s v -l version --description 'Gives version information.'
complete -c axohelp -s V --description 'NOT CURRENTLY IMPLEMENTED: Give information on each function used.'

