# bbox
# Autogenerated from man page /usr/share/man/man1/bbox.1.gz
# using Deroffing man parser
complete -c bbox -s h -l help --description 'Show summary of options.'
complete -c bbox -s V --description 'Show version of program.'
complete -c bbox -s r --description 'resolution of picture in dpi.'
complete -c bbox -s l --description 'loose bounding box (integer bounding box is exp… [See Man Page]'

