# bcp
# Autogenerated from man page /usr/share/man/man1/bcp.1.gz
# using Deroffing man parser
complete -c bcp -l boost --description 'sets the location of the Boost tree to path.'
complete -c bcp -l scan --description 'treat the module list as a list of (possibly no… [See Man Page]'
complete -c bcp -l cvs --description 'only copy files under CVS version control.'
complete -c bcp -l unix-lines --description 'make sure that all copied files use Unix style … [See Man Page]'
complete -c bcp -l help --description '.'

