# bf_copy-bdb
# Autogenerated from man page /usr/share/man/man1/bf_copy-bdb.1.gz
# using Deroffing man parser
complete -c bf_copy-bdb -s c --description 'option causes only active log files to be copied, not all.'

