# bf_copy
# Autogenerated from man page /usr/share/man/man1/bf_copy.1.gz
# using Deroffing man parser
complete -c bf_copy -s c --description 'option causes only active log files to be copied, not all.'

