# bf_tar
# Autogenerated from man page /usr/share/man/man1/bf_tar.1.gz
# using Deroffing man parser
complete -c bf_tar -s r --description 'option causes bf_tar to remove inactive log fil… [See Man Page]'
complete -c bf_tar -s R --description 'option causes bf_tar to remove inactive log fil… [See Man Page]'

