# bf_tar-bdb
# Autogenerated from man page /usr/share/man/man1/bf_tar-bdb.1.gz
# using Deroffing man parser
complete -c bf_tar-bdb -s r --description 'option causes bf_tar to remove inactive log fil… [See Man Page]'
complete -c bf_tar-bdb -s R --description 'option causes bf_tar to remove inactive log fil… [See Man Page]'

