# bibdoiadd
# Autogenerated from man page /usr/share/man/man1/bibdoiadd.1.gz
# using Type1
complete -c bibdoiadd -s c --description 'Configuration file.'
complete -c bibdoiadd -s f --description 'Force checking doi number even if one is present.'

