# bibtex
# Autogenerated from man page /Library/TeX/texbin/man/man1/bibtex.1
complete -c bibtex -o min-crossrefs --description 'option defines the minimum number of crossref required for automatic inclusio…'
complete -c bibtex -o terse --description 'option,  operates silently.'

