# bjam
# Autogenerated from man page /usr/share/man/man1/bjam.1.gz
# using Deroffing man parser
complete -c bjam -l prefix --description 'Install architecture independent files here.'
complete -c bjam -l exec-prefix --description 'Default; <PREFIX>.'
complete -c bjam -l libdir --description 'Install library files here.  Default; <EPREFIX>/lib.'
complete -c bjam -l includedir --description 'Install header files here.  Default; <PREFIX>/include.'
complete -c bjam -l stagedir --description 'Install library files here Default; . /stage .'
complete -c bjam -l build-type --description 'Build the specified pre-defined set of variatio… [See Man Page]'
complete -c bjam -l build-dir --description 'Build in this location instead of building with… [See Man Page]'
complete -c bjam -l show-libraries --description 'Display the list of Boost libraries that requir… [See Man Page]'
complete -c bjam -l layout --description 'Determine whether to choose library names and h… [See Man Page]'
complete -c bjam -l buildid --description 'Add the specified ID to the name of built libraries.'
complete -c bjam -l python-buildid --description 'Add the specified ID to the name of built libra… [See Man Page]'
complete -c bjam -l help --description 'This message.'
complete -c bjam -l 'with-<library>' --description 'Build and install the specified <library>.'
complete -c bjam -l 'without-<library>' --description 'Do not build, stage, or install the specified <library>.'

