# blkmapd
# Autogenerated from man page /usr/share/man/man8/blkmapd.8.gz
# using Deroffing man parser
complete -c blkmapd -s d --description 'Performs device discovery only then exits.'
complete -c blkmapd -s f --description 'Runs blkmapd in the foreground and sends output… [See Man Page]'

