# bogoupgrade
# Autogenerated from man page /usr/share/man/man1/bogoupgrade.1.gz
# using Deroffing man parser
complete -c bogoupgrade -s h --description 'option prints the help message and exits.'
complete -c bogoupgrade -s d --description 'specifies the directory with the wordlists for converting.'
complete -c bogoupgrade -s i --description 'specifies the input file to be converted.'
complete -c bogoupgrade -s o --description 'specifies the output Berkeley DB file.'
complete -c bogoupgrade -s b --description 'gives the path to the bogoutil command.'

