# bogolexer
# Autogenerated from man page /usr/share/man/man1/bogolexer.1.gz
# using Deroffing man parser
complete -c bogolexer -s p --description 'option tells bogolexer to print just the tokens… [See Man Page]'
complete -c bogolexer -s q --description 'option tells bogolexer to print a token count, … [See Man Page]'
complete -c bogolexer -s h --description 'option prints the help message and exits.'
complete -c bogolexer -s n --description 'option tells bogolexer to map non-ascii charact… [See Man Page]'
complete -c bogolexer -s v --description 'option increases the verbosity level.'
complete -c bogolexer -s x --description 'option allows setting of debug flags for printi… [See Man Page]'
complete -c bogolexer -o cfilename --description 'option tells bogolexer to read the config file named.'
complete -c bogolexer -s C --description 'option prevents bogolexer from reading configuration files.'
complete -c bogolexer -s D --description 'option redirects the debugging output to stdout… [See Man Page]'
complete -c bogolexer -s I --description 'option tells bogolexer to read its input from t… [See Man Page]'
complete -c bogolexer -s O --description 'option tells bogolexer to write its output to t… [See Man Page]'
complete -c bogolexer -s V --description 'option prints the version number and exits.  AUTHOR.'

