# bogotune
# Autogenerated from man page /usr/share/man/man1/bogotune.1.gz
# using Deroffing man parser
complete -c bogotune -s h --description 'option prints the help message and exits.'
complete -c bogotune -s v --description 'option increases the verbosity level.'
complete -c bogotune -s c --description 'filename option tells bogofilter to read the config file named.'
complete -c bogotune -s C --description 'option prevents bogotune from reading a configuration file.'
complete -c bogotune -s d --description 'dir option specifies the directory for the database.'
complete -c bogotune -s D --description 'option tells bogotune to build a wordlist in me… [See Man Page]'
complete -c bogotune -s n --description 'option tells bogotune that the following argume… [See Man Page]'
complete -c bogotune -s s --description 'option will be treated as though they had been preceded by.'
complete -c bogotune -o 's.' --description '.'
complete -c bogotune -s r --description 'option tells bogotune to use the following para… [See Man Page]'
complete -c bogotune -s T --description 'option tells bogotune to use the following para… [See Man Page]'
complete -c bogotune -s M --description 'option tells bogotune to convert the file to me… [See Man Page]'
complete -c bogotune -o ddir --description 'option.'

