# bsondump
# Autogenerated from man page /usr/share/man/man1/bsondump.1.gz
# using Deroffing man parser
complete -c bsondump -l help --description 'Returns information on the options and use of bsondump.'
complete -c bsondump -l verbose -s v --description 'Increases the amount of internal reporting retu… [See Man Page]'
complete -c bsondump -l quiet --description 'Runs the bsondump in a quiet mode that attempts… [See Man Page]'
complete -c bsondump -l version --description 'Returns the bsondump release number. UNINDENT NDENT 0. 0.'
complete -c bsondump -l objcheck --description 'Validates each BSON object before outputting it in JSON format.'
complete -c bsondump -l noobjcheck --description 'New in version 2. 4.'
complete -c bsondump -l type --description 'Changes the operation of bsondump from outputti… [See Man Page]'
complete -c bsondump -l pretty --description 'New in version 3. 0. 0.'

