# btattach
# Autogenerated from man page /usr/share/man/man1/btattach.1.gz
# using Deroffing man parser
complete -c btattach -s B -l bredr --description 'Attach a BR/EDR controller.'
complete -c btattach -s A -l amp --description 'Attach an AMP controller.'
complete -c btattach -s P -l protocol --description 'Specify the protocol type for talking to the device.'
complete -c btattach -s R --description 'Set the device into raw mode (the kernel and bl… [See Man Page]'

