# buildserver
# Autogenerated from man page /usr/share/man/man8/buildserver.8
# using Deroffing man parser
complete -c buildserver -s C -l configure --description 'performs the configuration portion of the build only.'
complete -c buildserver -s d -l database --description 'provides the name of an alternate database to u… [See Man Page]'
complete -c buildserver -s f -l config_dir --description 'provides the name of an alternate location for … [See Man Page]'

