# cairo-clock
# Autogenerated from man page /usr/share/man/man1/cairo-clock.1.gz
# using Deroffing man parser
complete -c cairo-clock -s x -l xposition --description 'br The initial x-position of the top-left windo… [See Man Page]'
complete -c cairo-clock -s y -l yposition --description 'br The initial y-position of the top-left windo… [See Man Page]'
complete -c cairo-clock -s w -l width --description 'br Initially open the window of the clock with … [See Man Page]'
complete -c cairo-clock -s g -l height --description 'br Initially open the window of the clock with … [See Man Page]'
complete -c cairo-clock -s s -l seconds --description 'br Passing this means to render the seconds-hand.'
complete -c cairo-clock -s d -l date --description 'br Passing this means to render the date-display.'
complete -c cairo-clock -s l -l list --description 'br List all themes installed system-wide and lo… [See Man Page]'
complete -c cairo-clock -s t -l theme --description 'br Use theme NAME for rendering.'
complete -c cairo-clock -s o -l ontop --description 'br Passing this means the clock-window will sta… [See Man Page]'
complete -c cairo-clock -s p -l pager --description 'br Passing this means the clock-window will app… [See Man Page]'
complete -c cairo-clock -s b -l taskbar --description 'br Passing this means the clock-window will sho… [See Man Page]'
complete -c cairo-clock -s i -l sticky --description 'br Passing this means to have the clock-window … [See Man Page]'
complete -c cairo-clock -s e -l twelve --description 'br Passing this will force the hour hand to use… [See Man Page]'
complete -c cairo-clock -s f -l twentyfour --description 'br Passing this will cause the hour hand to spr… [See Man Page]'
complete -c cairo-clock -s r -l refresh --description 'br Use an animation-refreshrate of RATE for rendering.'
complete -c cairo-clock -s h -l help --description 'br Print a usage-description and exit.'
complete -c cairo-clock -s v -l version --description '.'

