# ccx
# Autogenerated from man page /usr/share/man/man1/ccx.1.gz
# using Deroffing man parser
complete -c ccx -s i --description 'Start the solver with the name <jobname>.  This is also the  .'
complete -c ccx -s o --description '.'
complete -c ccx -s v -l version --description 'Prints the version number.'

