# cdxa2mpeg
# Autogenerated from man page /usr/share/man/man1/cdxa2mpeg.1.gz
# using Deroffing man parser
complete -c cdxa2mpeg -s v -l verbose --description 'be verbose.'
complete -c cdxa2mpeg -s q -l quiet --description 'show only critical messages.'
complete -c cdxa2mpeg -s V -l version --description 'display version and copyright information and exit .'
complete -c cdxa2mpeg -s '?' -l help --description 'Show this help message.'
complete -c cdxa2mpeg -l usage --description 'Display brief usage message AUTHOR Written by H… [See Man Page]'

