# certcheck
# Autogenerated from man page /usr/share/man/man8/certcheck.8
# using Deroffing man parser
complete -c certcheck -s n -l new_key --description 'for this computer.'
complete -c certcheck -s H -l help --description '.'
complete -c certcheck -s V --description '.'
complete -c certcheck -s h -l host --description '.'
complete -c certcheck -s a -l all --description '.'
complete -c certcheck -s c -l client --description '                        and certificates as necessary.'

