# chime2jmol
# Autogenerated from man page /usr/share/man/man1/chime2jmol.1.gz
# using Type1
complete -c chime2jmol -s s --description 'Specify source directory.'
complete -c chime2jmol -s d --description 'Specify destination directory.'
complete -c chime2jmol -s c --description 'Clear destination directory.'
complete -c chime2jmol -s a --description 'Specify alternate archive name.'
complete -c chime2jmol -s b --description 'Specify codebase.'

