# clang-tidy-3
# Autogenerated from man page /usr/share/man/man1/clang-tidy-3.5.1.gz
# using Deroffing man parser
complete -c clang-tidy-3 -o analyze-temporary-dtors --description 'clang-analyzer- checks.'
complete -c clang-tidy-3 -o checks --description 'prefix.'
complete -c clang-tidy-3 -o header-filter --description 'headers to output diagnostics from.'
complete -c clang-tidy-3 -o line-filter --description 'warnings.  Can be used together with -header-filter.'
complete -c clang-tidy-3 -o help --description '.'
complete -c clang-tidy-3 -o help-list --description '.'
complete -c clang-tidy-3 -o version --description '.'
complete -c clang-tidy-3 -o fix --description '.'
complete -c clang-tidy-3 -o 'header-filter.' --description 'array of objects:.'
complete -c clang-tidy-3 -o list-checks --description '.'
complete -c clang-tidy-3 -s p --description '.'

