# composeglyphs
# Autogenerated from man page /usr/share/man/man1/composeglyphs.1.gz
# using Deroffing man parser
complete -c composeglyphs -s e --description 'The base encoding AFM to use.'
complete -c composeglyphs -s E --description 'The encoding vector to output.'
complete -c composeglyphs -s i --description 'The AFM of the original font.'
complete -c composeglyphs -s o --description 'The font program to generate.'
complete -c composeglyphs -s c --description 'The AFM containing supplementary composite char… [See Man Page]'
complete -c composeglyphs -s n --description 'The name of the new font.'
complete -c composeglyphs -s t --description 'The target encoding.'
complete -c composeglyphs -s a --description 'The name of the AFM file to generate.'

