# compiz
# Autogenerated from man page /usr/share/man/man1/compiz.1.gz
# using Deroffing man parser
complete -c compiz -l debug --description 'Enable debug mode.'
complete -c compiz -l display --description 'Manage the display called  DISPLAY instead of t… [See Man Page]'
complete -c compiz -l help --description 'Shows a summary of options and exit.'
complete -c compiz -l keep-desktop-hints --description 'Retains existing desktop hints.'
complete -c compiz -l no-auto-add-ccp --description 'Do not automatically load the Compiz config plugin (ccp).'
complete -c compiz -l replace --description 'Replaces any existing window managers on the given X display.'
complete -c compiz -l send-startup-message --description 'Sends a message to all connected X clientd once… [See Man Page]'
complete -c compiz -l sm-disable --description 'Disables session management.'
complete -c compiz -l sm-client-id --description 'Uses the given  ID as the client ID for session management.'
complete -c compiz -l sync --description 'Makes all X calls synchronous.'
complete -c compiz -l version --description 'Prints the version of the program and exits.'

