# convcal
# Autogenerated from man page /usr/share/man/man1/convcal.1.gz
# using Deroffing man parser
complete -c convcal -s h --description 'prints the help message on stderr and exits successfully.'
complete -c convcal -s i --description 'set user\'s choice for input format, supported f… [See Man Page]'
complete -c convcal -s o --description 'force output format, supported formats are iso,… [See Man Page]'
complete -c convcal -s r --description 'set reference date (the date is read using the … [See Man Page]'
complete -c convcal -s w --description 'set the wrap year to year.'

