# convertall
# Autogenerated from man page /usr/share/man/man1/convertall.1.gz
# using Deroffing man parser
complete -c convertall -s d -l decimals --description 'set number of decimals to show.'
complete -c convertall -s f -l fixed-decimals --description 'show set number of decimals, even if zeros.'
complete -c convertall -s h -l help --description 'display this message and exit.'
complete -c convertall -s i -l interactive --description 'interactive command line mode (non-GUI).'
complete -c convertall -s q -l quiet --description 'convert without further prompts.'
complete -c convertall -s s -l sci-notation --description 'show results in scientific notation.'
complete -c convertall -o or- --description 'convertall [options] [number] from_unit [to_unit].'

