# cppunit-config
# Autogenerated from man page /usr/share/man/man1/cppunit-config.1.gz
# using Deroffing man parser
complete -c cppunit-config -l version --description 'Print the currently installed version of cppuni… [See Man Page]'
complete -c cppunit-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c cppunit-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c cppunit-config -l prefix --description 'Print the prefix with which cppunit was compiled.'
complete -c cppunit-config -l exec-prefix --description 'Print the exec-prefix with which cppunit was compiled.'

