# crywrap
# Autogenerated from man page /usr/share/man/man8/crywrap.8.gz
# using Deroffing man parser
complete -c crywrap -l destionation --description 'The destionation host and address, where CryWra… [See Man Page]'
complete -c crywrap -l anon --description 'Enables Anon-DH mode.'
complete -c crywrap -l cert --description '.'
complete -c crywrap -l key --description '.'
complete -c crywrap -l ca --description '.'
complete -c crywrap -l verify --description 'Set the level of client certificate verification.'
complete -c crywrap -l inetd --description 'Enable inetd-mode.'
complete -c crywrap -l listen --description 'The host and port CryWrap should listen on.'
complete -c crywrap -l pidfile --description 'Write the pid thy runs with to PIDFILE .'
complete -c crywrap -l user --description 'UID is the numerical user id of the user thy should run as.'
complete -c crywrap -l version --description 'Print the version number and exit.'
complete -c crywrap -l help --description 'Print a verbose help screen and exit.'
complete -c crywrap -l usage --description 'Print a short summary of options.  EXAMPLES Setting up pop3s.'

