# darktable
# Autogenerated from man page /usr/share/man/man1/darktable.1.gz
# using Type1
complete -c darktable -s d --description 'This option enables debug output to the terminal.'
complete -c darktable -l disable-opencl --description 'Prevent darktable from initializing the OpenCL subsystem.'
complete -c darktable -l library --description 'darktable keeps image information in an sqlite … [See Man Page]'
complete -c darktable -l datadir --description 'This option defines the directory where darktab… [See Man Page]'
complete -c darktable -l moduledir --description 'darktable has a modular structure and organizes… [See Man Page]'
complete -c darktable -l tmpdir --description 'The place where darktable stores its temporary files.'
complete -c darktable -l configdir --description 'This option defines the directory where darktab… [See Man Page]'
complete -c darktable -l cachedir --description 'darktable keeps a cache of image thumbnails for… [See Man Page]'
complete -c darktable -l localedir --description 'The place where darktable finds its language sp… [See Man Page]'
complete -c darktable -l luacmd --description 'A string containing lua commands to execute aft… [See Man Page]'
complete -c darktable -l conf --description 'darktable supports a rich set of configuration … [See Man Page]'

