# darktable-cli
# Autogenerated from man page /usr/share/man/man1/darktable-cli.1.gz
# using Type1
complete -c darktable-cli -l width --description 'This optional parameter allows one to limit the… [See Man Page]'
complete -c darktable-cli -l height --description 'This optional parameter allows one to limit the… [See Man Page]'
complete -c darktable-cli -l bpp --description 'An optional parameter to define the bit depth o… [See Man Page]'
complete -c darktable-cli -l hq --description 'A flag that defines whether to use high quality… [See Man Page]'
complete -c darktable-cli -l upscale --description 'A flag that defines whether to allow upscaling during export.'
complete -c darktable-cli -l verbose --description 'Enables verbose output.'

