# dfu-tool
# Autogenerated from man page /usr/share/man/man1/dfu-tool.1.gz
# using Type1
complete -c dfu-tool -l help --description 'Show summary of all the commands available for use.'
complete -c dfu-tool -l version --description 'Show the version of dfu-tool installed.'
complete -c dfu-tool -l verbose --description 'Show extra debugging information.'
complete -c dfu-tool -l device --description 'If multiple DFU-capable devices are attached yo… [See Man Page]'
complete -c dfu-tool -l transfer-size --description 'Manually override the size of each USB transfer… [See Man Page]'

