# dh_strip
# Autogenerated from man page /usr/share/man/man1/dh_strip.1.gz
# using Type1
complete -c dh_strip -o Xitem -l exclude --description 'Exclude files that contain item anywhere in the… [See Man Page]'
complete -c dh_strip -l dbg-package --description 'This option is a now special purpose option tha… [See Man Page]'
complete -c dh_strip -s k -l keep-debug --description 'This option is a now special purpose option tha… [See Man Page]'
complete -c dh_strip -l dbgsym-migration --description 'This option is used to migrate from a manual \\*… [See Man Page]'
complete -c dh_strip -l automatic-dbgsym -l no-automatic-dbgsym --description 'Control whether dh_strip should be creating deb… [See Man Page]'
complete -c dh_strip -l ddebs -l no-ddebs --description 'Historical name for --automatic-dbgsym and --no… [See Man Page]'

