# diameterc
# Autogenerated from man page /usr/share/man/man1/diameterc.1.gz
# using Deroffing man parser
complete -c diameterc -s i --description 'Prepend the specified directory to the code path.'
complete -c diameterc -s o --description 'Write generated source to the specified directory.'
complete -c diameterc -o E: --description '.'
complete -c diameterc -o H: --description 'Suppress erl and hrl generation, respectively.'
complete -c diameterc -l name --description '.'
complete -c diameterc -l prefix --description 'Transform the input dictionary before compilati… [See Man Page]'
complete -c diameterc -l inherits --description 'Transform the input dictionary before compilati… [See Man Page]'

