# dig
# Autogenerated from man page /usr/share/man/man1/dig.1.gz
# using Deroffing man parser
complete -c dig -s 4 --description 'Use IPv4 only.'
complete -c dig -s 6 --description 'Use IPv6 only.'
complete -c dig -s b --description 'Set the source IP address of the query.'
complete -c dig -s c --description 'Set the query class.'
complete -c dig -s f --description 'Batch mode: dig reads a list of lookup requests… [See Man Page]'
complete -c dig -s i --description 'Do reverse IPv6 lookups using the obsolete RFC1… [See Man Page]'
complete -c dig -s k --description 'Sign queries using TSIG using a key read from the given file.'
complete -c dig -s m --description 'Enable memory usage debugging.'
complete -c dig -s p --description 'Send the query to a non-standard port on the se… [See Man Page]'
complete -c dig -s q --description 'The domain name to query.'
complete -c dig -s t --description 'The resource record type to query.'
complete -c dig -s v --description 'Print the version number and exit.'
complete -c dig -s x --description 'Simplified reverse lookups, for mapping addresses to names.'
complete -c dig -s y --description 'Sign queries using TSIG with the given authentication key.'
complete -c dig -s h --description 'option is given.'

