# djvuxmlparser
# Autogenerated from man page /usr/share/man/man1/djvuxmlparser.1.gz
# using Deroffing man parser
complete -c djvuxmlparser -l page --description 'Select a page in a multi-page document.'
complete -c djvuxmlparser -l with-text --description 'Specifies the  HIDDENTEXT  element for each pag… [See Man Page]'
complete -c djvuxmlparser -l with-anno --description 'flag then the.'
complete -c djvuxmlparser -l without-anno --description 'is implied.   If none of the  .'
complete -c djvuxmlparser -l without-text --description '.'
complete -c djvuxmlparser -s o --description 'In principle the target DjVu file is the file  … [See Man Page]'

