# djvubind
# Autogenerated from man page /usr/share/man/man1/djvubind.1.gz
# using Deroffing man parser
complete -c djvubind -l bookmarks --description 'Specifies an alternate bookmarks file.'
complete -c djvubind -l cover-front --description 'Specifies an alternate front cover image.'
complete -c djvubind -l cover-back --description 'Specifies an alternate back cover image.'
complete -c djvubind -l metadata --description 'Specifies an alternate metadata file.'
complete -c djvubind -l no-ocr --description 'Images will not be processed for text content.'
complete -c djvubind -l ocr-engine --description 'Specifies which ocr engine to use.   Tesseract is the default.'
complete -c djvubind -l tesseract-options --description 'Passes custom options to the respective ocr eng… [See Man Page]'
complete -c djvubind -l title-start --description 'Prior to this image, pages will be titled with … [See Man Page]'
complete -c djvubind -l title-uppercase --description 'Roman numeral titles will be in uppercase (I, II, III. ).'
complete -c djvubind -l title-exclude --description 'This image will not be included in sequential page titling.'
complete -c djvubind -s q -l quiet --description 'No status information will be given.'
complete -c djvubind -s v -l verbose --description 'Additional information will be given, which is … [See Man Page]'
complete -c djvubind -l cuneiform-options --description '.'

