# docker-trust-key-generate
# Autogenerated from man page /usr/share/man/man1/docker-trust-key-generate.1.gz
# using Deroffing man parser
complete -c docker-trust-key-generate -l dir --description '    Directory to generate key in, defaults to c… [See Man Page]'
complete -c docker-trust-key-generate -s h -l 'help[' --description '    help for generate SEE ALSO.'

