# docker-restart
# Autogenerated from man page /usr/share/man/man1/docker-restart.1.gz
# using Deroffing man parser
complete -c docker-restart -s h -l 'help[' --description '    help for restart.'
complete -c docker-restart -s t -l time --description '    Seconds to wait for stop before killing the… [See Man Page]'

