# docker-stack-rm
# Autogenerated from man page /usr/share/man/man1/docker-stack-rm.1.gz
# using Deroffing man parser
complete -c docker-stack-rm -s h -l 'help[' --description '    help for rm SEE ALSO.'

