# docker-service-rollback
# Autogenerated from man page /usr/share/man/man1/docker-service-rollback.1.gz
# using Deroffing man parser
complete -c docker-service-rollback -s d -l 'detach[' --description '    Exit immediately instead of waiting for the… [See Man Page]'
complete -c docker-service-rollback -s h -l 'help[' --description '    help for rollback.'
complete -c docker-service-rollback -s q -l 'quiet[' --description '    Suppress progress output SEE ALSO.'

