# docker-rename
# Autogenerated from man page /usr/share/man/man1/docker-rename.1.gz
# using Deroffing man parser
complete -c docker-rename -s h -l 'help[' --description '    help for rename SEE ALSO.'

