# docker-stack-ls
# Autogenerated from man page /usr/share/man/man1/docker-stack-ls.1.gz
# using Deroffing man parser
complete -c docker-stack-ls -l format --description '    Pretty-print stacks using a Go template.'
complete -c docker-stack-ls -s h -l 'help[' --description '    help for ls SEE ALSO.'

