# docker-deploy
# Autogenerated from man page /usr/share/man/man1/docker-deploy.1.gz
# using Deroffing man parser
complete -c docker-deploy -l bundle-file --description '    Path to a Distributed Application Bundle file.'
complete -c docker-deploy -s c -l compose-file --description '    Path to a Compose file.'
complete -c docker-deploy -s h -l 'help[' --description '    help for deploy.'
complete -c docker-deploy -l 'prune[' --description '    Prune services that are no longer referenced.'
complete -c docker-deploy -l resolve-image --description '    Query the registry to resolve image digest … [See Man Page]'
complete -c docker-deploy -l 'with-registry-auth[' --description '    Send registry authentication details to Swa… [See Man Page]'

