# docker-checkpoint
# Autogenerated from man page /usr/share/man/man1/docker-checkpoint.1.gz
# using Deroffing man parser
complete -c docker-checkpoint -s h -l 'help[' --description '    help for checkpoint SEE ALSO.'

