# docker-version
# Autogenerated from man page /usr/share/man/man1/docker-version.1.gz
# using Deroffing man parser
complete -c docker-version -s f -l format --description '    Format the output using the given Go template.'
complete -c docker-version -s h -l 'help[' --description '    help for version SEE ALSO.'

