# docker-container
# Autogenerated from man page /usr/share/man/man1/docker-container.1.gz
# using Deroffing man parser
complete -c docker-container -s h -l 'help[' --description '    help for container SEE ALSO.'

