# docker-image-pull
# Autogenerated from man page /usr/share/man/man1/docker-image-pull.1.gz
# using Deroffing man parser
complete -c docker-image-pull -s a -l 'all-tags)' --description 'This command pulls all images from the fedora r… [See Man Page]'
complete -c docker-image-pull -l 'all-tags[' --description '    Download all tagged images in the repository.'
complete -c docker-image-pull -l 'disable-content-trust[' --description '    Skip image verification.'
complete -c docker-image-pull -s h -l 'help[' --description '    help for pull.'
complete -c docker-image-pull -l platform --description '    Set platform if server is multi-platform capable SEE ALSO.'

