# docker-trust-inspect
# Autogenerated from man page /usr/share/man/man1/docker-trust-inspect.1.gz
# using Deroffing man parser
complete -c docker-trust-inspect -s h -l 'help[' --description '    help for inspect SEE ALSO.'

