# docker-trust-signer-remove
# Autogenerated from man page /usr/share/man/man1/docker-trust-signer-remove.1.gz
# using Deroffing man parser
complete -c docker-trust-signer-remove -s f -l 'force[' --description '    Do not prompt for confirmation before remov… [See Man Page]'
complete -c docker-trust-signer-remove -s h -l 'help[' --description '    help for remove SEE ALSO.'

