# docker-node-promote
# Autogenerated from man page /usr/share/man/man1/docker-node-promote.1.gz
# using Deroffing man parser
complete -c docker-node-promote -s h -l 'help[' --description '    help for promote SEE ALSO.'

