# dolfin-plot
# Autogenerated from man page /usr/share/man/man1/dolfin-plot.1.gz
# using Deroffing man parser
complete -c dolfin-plot -s h -l help --description 'Display detailed help text and exit.'

