# dolfin-convert
# Autogenerated from man page /usr/share/man/man1/dolfin-convert.1.gz
# using Deroffing man parser
complete -c dolfin-convert -s h -l help --description 'Display help text and exit.'
complete -c dolfin-convert -s i -l input --description 'Specify input format.'
complete -c dolfin-convert -s o -l output --description 'Specify output format. PP Supported formats:.'
complete -c dolfin-convert -s g --description '.'

