# doxypy
# Autogenerated from man page /usr/share/man/man1/doxypy.1.gz
# using Deroffing man parser
complete -c doxypy -s h -l help --description 'Show summary of options.'
complete -c doxypy -l version --description 'Show version of program.'
complete -c doxypy -l autobrief --description 'Use the docstring summary line as \\\\brief description.'
complete -c doxypy -l debug --description 'Enable debug output on stderr.'

