# dpkg-parsechangelog
# Autogenerated from man page /usr/share/man/man1/dpkg-parsechangelog.1.gz
# using Deroffing man parser
complete -c dpkg-parsechangelog -s l --description 'Specifies the changelog file to read information from.'
complete -c dpkg-parsechangelog -s F --description 'Specifies the format of the changelog.'
complete -c dpkg-parsechangelog -s L --description 'Specify an additional directory to search for parser scripts.'
complete -c dpkg-parsechangelog -s S -l show-field --description 'Specifies the name of the field to show (since dpkg 1. 17. 0).'
complete -c dpkg-parsechangelog -s '?' -l help --description 'Show the usage message and exit.'
complete -c dpkg-parsechangelog -l version --description 'Show the version and exit.'
complete -c dpkg-parsechangelog -l file --description 'Set the changelog filename to parse.'
complete -c dpkg-parsechangelog -l label --description 'Set the name of the changelog file to use in er… [See Man Page]'
complete -c dpkg-parsechangelog -l format --description 'Set the output format.'
complete -c dpkg-parsechangelog -l all --description 'Include all changes.'
complete -c dpkg-parsechangelog -s s -l since --description 'TQ  -v " version" Include all changes later than version.'
complete -c dpkg-parsechangelog -s u -l until --description 'Include all changes earlier than version.'
complete -c dpkg-parsechangelog -s f -l from --description 'Include all changes equal or later than version.'
complete -c dpkg-parsechangelog -s t -l to --description 'Include all changes up to or equal than version.'
complete -c dpkg-parsechangelog -s c -l count --description 'TQ  -n " number" Include number entries from th… [See Man Page]'
complete -c dpkg-parsechangelog -s v --description 'Include all changes later than version.'
complete -c dpkg-parsechangelog -s n --description 'Include number entries from the top (or the tai… [See Man Page]'
complete -c dpkg-parsechangelog -s o -l offset --description 'Change the starting point for --count, counted … [See Man Page]'

