# dus
# Autogenerated from man page /usr/share/man/man8/dus.8.gz
# using Deroffing man parser
complete -c dus -s d --description 'Select dialog menus if available.'
complete -c dus -s h --description 'Print a summary of command line options and exit.'
complete -c dus -s t --description 'Select a plain text interface.'
complete -c dus -s v --description 'Print the current version and exit.'
complete -c dus -s z --description 'Select zenity menus if available (default).'

