# elixir
# Autogenerated from man page /usr/share/man/man1/elixir.1.gz
# using Darwin man parser
complete -c elixir -s e --description 'Evaluates the specified expression.'
complete -c elixir -s r --description 'Requires the specified file.'
complete -c elixir -s S --description 'Runs the specified script.'
complete -c elixir -o pa --description 'Adds the specified directory to the beginning of the code path.'
complete -c elixir -o pr --description 'Does the same thing as r see above but in parallel.'
complete -c elixir -o pz --description 'Adds the specified directory to the end of the code path.'
complete -c elixir -l app --description 'Starts the specified application and all its dependencies.'
complete -c elixir -l erl --description 'Serves the same purpose as ELIXIR_ERL_OPTIONS s… [See Man Page]'
complete -c elixir -l cookie --description 'Specifies the magic cookie value.'
complete -c elixir -l detached --description 'Runs the Erlang runtime system detached from th… [See Man Page]'
complete -c elixir -l hidden --description 'Starts a hidden node.'
complete -c elixir -l sname --description 'Gives a node a short name and starts it.'
complete -c elixir -l name --description 'Gives a node a long name and starts it.'
complete -c elixir -l no-halt --description 'Does not halt the Erlang VM after execution.'

