# empy
# Autogenerated from man page /usr/share/man/man1/empy.1.gz
# using Deroffing man parser
complete -c empy -s h -l help --description 'Show summary of options.'
complete -c empy -s v -l version --description 'Show version of program.  SEE ALSO python (1).'

