# evcd2vcd
# Autogenerated from man page /usr/share/man/man1/evcd2vcd.1.gz
# using Type1
complete -c evcd2vcd -s f -l filename --description 'Specify EVCD input filename.'
complete -c evcd2vcd -s h -l help --description 'Show help screen.'

