# ffcfstress
# Autogenerated from man page /usr/share/man/man1/ffcfstress.1.gz
# using Deroffing man parser
complete -c ffcfstress -s d --description 'The device to test (by default /dev/input/event0).'
complete -c ffcfstress -s u --description 'The update rate in Hz (25 by default).'
complete -c ffcfstress -s f --description 'The spring center motion frequency in Hz (0. 1 by default).'
complete -c ffcfstress -s a --description 'The spring center motion amplitude, between 0. 0 and 1. 0 (1.'
complete -c ffcfstress -s s --description 'The spring strength factor (1. 0 by default).'
complete -c ffcfstress -s x --description 'absolute axis to test (default: 0) .'
complete -c ffcfstress -s A --description 'switch off auto-centering.'
complete -c ffcfstress -s o --description 'Dummy option, useful when all defaults should be used.'

