# ffset
# Autogenerated from man page /usr/share/man/man1/ffset.1.gz
# using Deroffing man parser
complete -c ffset -s g --description 'The gain (0-100).'
complete -c ffset -s a --description 'The autocenter strength (0-100).'

