# fig2mpdf
# Autogenerated from man page /usr/share/man/man1/fig2mpdf.1.gz
# using Deroffing man parser
complete -c fig2mpdf -s e --description 'produce an eps output file.'
complete -c fig2mpdf -s p --description 'explicitly set the ranges of depths for splitti… [See Man Page]'
complete -c fig2mpdf -s i --description 'include the the bottommost range (that is, the … [See Man Page]'
complete -c fig2mpdf -s I --description 'turn on pyramid mode.'
complete -c fig2mpdf -s g --description 'set the allowed gapwidth between two used depth… [See Man Page]'
complete -c fig2mpdf -s s --description 'replace the default style for selecting a font … [See Man Page]'
complete -c fig2mpdf -s H --description 'replace the default header sequence for creatin… [See Man Page]'
complete -c fig2mpdf -s G --description 'in multilayer mode change the default output fi… [See Man Page]'
complete -c fig2mpdf -s v --description 'be verbose and print out all executed commands.'
complete -c fig2mpdf -s V --description 'print out the version of fig2mpdf.'
complete -c fig2mpdf -o 'I.' --description '.'

