# FileCheck-4
# Autogenerated from man page /usr/share/man/man1/FileCheck-4.0.1.gz
# using Deroffing man parser
complete -c FileCheck-4 -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c FileCheck-4 -l check-prefix --description 'FileCheck searches the contents of match-filena… [See Man Page]'
complete -c FileCheck-4 -l check-prefixes --description 'An alias of \\%--check-prefix that allows multip… [See Man Page]'
complete -c FileCheck-4 -l input-file --description 'File to check (defaults to stdin). UNINDENT NDENT 0. 0.'
complete -c FileCheck-4 -l match-full-lines --description 'By default, FileCheck allows matches of anywhere on a line.'
complete -c FileCheck-4 -l strict-whitespace --description 'By default, FileCheck canonicalizes input horiz… [See Man Page]'
complete -c FileCheck-4 -l implicit-check-not --description 'Adds implicit negative checks for the specified… [See Man Page]'
complete -c FileCheck-4 -o 'verify.' --description 'warnings not covered by any CHECK: patterns.'
complete -c FileCheck-4 -o version --description 'Show the version number of this program.'

