# findmatchingentities
# Autogenerated from man page /usr/share/man/man1/findmatchingentities.1
# using Deroffing man parser
complete -c findmatchingentities -s H -l help --description 'prints this help command and exits normally.'
complete -c findmatchingentities -s V -l version --description 'prints the version information for this program… [See Man Page]'
complete -c findmatchingentities -s c -l check --description 'forces the check that confirms that the databas… [See Man Page]'

