# fop-ttfreader
# Autogenerated from man page /usr/share/man/man1/fop-ttfreader.1.gz
# using Type1
complete -c fop-ttfreader -o enc --description 'with this option you can create a WinAnsi encoded font.'
complete -c fop-ttfreader -o ttcname --description 'if you\'re reading data from TrueType Collection (.'

