# freecadcmd
# Autogenerated from man page /usr/share/man/man1/freecadcmd.1.gz
# using Deroffing man parser
complete -c freecadcmd -s h -l help --description 'Show summary of options.'
complete -c freecadcmd -s v -l version --description 'Show version of program.'
complete -c freecadcmd -s c -l console --description 'Start in console mode.'
complete -c freecadcmd -l response-file --description 'Can be specified with \'@name\', too. SS "Configuration".'
complete -c freecadcmd -s l -l write-log --description 'Write a log file.'
complete -c freecadcmd -s t -l run-test --description 'Test level.'
complete -c freecadcmd -s M -l module-path --description 'Additional module path.'
complete -c freecadcmd -s P -l python-path --description 'Additional Python path.'

