# freecad-thumbnailer
# Autogenerated from man page /usr/share/man/man1/freecad-thumbnailer.1.gz
# using Deroffing man parser
complete -c freecad-thumbnailer -s s --description 'Specify the size of the image in pixel.'

