# fst2vcd
# Autogenerated from man page /usr/share/man/man1/fst2vcd.1.gz
# using Type1
complete -c fst2vcd -s f -l fstname --description 'Specify FST input filename.'
complete -c fst2vcd -s o -l output --description 'Specify optional VCD output filename.'
complete -c fst2vcd -s e -l 'extensions\\Fr' --description 'Emit FST extensions to VCD.'

