# fstminer
# Autogenerated from man page /usr/share/man/man1/fstminer.1.gz
# using Type1
complete -c fstminer -s d -l dumpfile --description 'Specify FST input dumpfile.'
complete -c fstminer -s m -l match --description 'Specifies "bitwise" match data (binary, real, string).'
complete -c fstminer -s x -l hex --description 'Specifies hexadecimal match data that will auto… [See Man Page]'
complete -c fstminer -s n -l namesonly --description 'Indicates that only facnames should be printed … [See Man Page]'
complete -c fstminer -s c -l comprehensive --description 'Indicates that results are not to stop after the first match.'

