# ftdi_eeprom
# Autogenerated from man page /usr/share/man/man1/ftdi_eeprom.1.gz
# using Deroffing man parser
complete -c ftdi_eeprom -l read-eeprom --description 'Read eeprom and write to -filename- from config-file.'
complete -c ftdi_eeprom -l erase-eeprom --description 'Erase eeprom.'
complete -c ftdi_eeprom -l flash-eeprom --description 'Flash eeprom.'

