# gac
# Autogenerated from man page /usr/share/man/man1/gac.1.gz
# using Deroffing man parser
complete -c gac -s c -s d --description 'a  new kernel, which contains the compiled code… [See Man Page]'
complete -c gac -s C --description 'Only compiles the input files to C code, which … [See Man Page]'
complete -c gac -s r --description 'Statically compiled files will be assumed to be… [See Man Page]'
complete -c gac -s o --description 'Name the output file <output>.'
complete -c gac -o ffast-int-arith --description 'Emit  code for  arithmetic operations, which wo… [See Man Page]'
complete -c gac -o ffast-plain-lists --description 'Emit code for list access, which works faster i… [See Man Page]'
complete -c gac -o ffast-list-funcs --description 'Inline  the functions \'Add\' and \'Length\' the co… [See Man Page]'
complete -c gac -o fno-check-types --description 'Emit  no error checks  for list access, which m… [See Man Page]'
complete -c gac -s p --description 'Pass the option  <option> to  the C compiler.'
complete -c gac -s P --description 'Pass the option  <option> to  the C linker.  SEE ALSO gap(1).'

