# gapd
# Autogenerated from man page /usr/share/man/man8/gapd.8.gz
# using Deroffing man parser
complete -c gapd -s h --description 'Start at host HOST: HOST may be given as machin… [See Man Page]'
complete -c gapd -s a --description 'Set server address to the one given by hostname(1).'
complete -c gapd -s l --description 'Start at localhost: reject incoming any connect… [See Man Page]'
complete -c gapd -s u --description 'Start in `universal\' mode: accept all incoming connections.'
complete -c gapd -s p --description 'Set server port to PORT, default port set in `/… [See Man Page]'
complete -c gapd -s t --description 'Redirect the server session output according to… [See Man Page]'
complete -c gapd -l infolevel-scscp --description 'Set the GAP InfoLevel for SCSCP to LEVEL.'
complete -c gapd -l infolevel-master --description 'Set the GAP InfoLevel for MasterWorker to LEVEL.'
complete -c gapd -l infolevel --description 'Indiscriminately set the GAP InfoLevel_s to LEVEL.'
complete -c gapd -l help --description 'Print this help text and exit.'
complete -c gapd -l version --description 'Output version information and exit.'

