# gazebo
# Autogenerated from man page /usr/share/man/man1/gazebo.1.gz
# using Type1
complete -c gazebo -s v -l version --description 'Output version information.'
complete -c gazebo -l verbose --description 'Increase the messages written to the terminal.'
complete -c gazebo -s h -l help --description 'Produce this help message.'
complete -c gazebo -s u -l pause --description 'Start the server in a paused state.'
complete -c gazebo -s e -l physics --description 'Specify a physics engine (ode|bullet|dart|simbody).'
complete -c gazebo -s p -l play --description 'Play a log file.'
complete -c gazebo -s r -l record --description 'Record state data.'
complete -c gazebo -l record_encoding --description 'Compression encoding format for log data (zlib|bz2|txt).'
complete -c gazebo -l record_path --description 'Absolute path in which to store state data.'
complete -c gazebo -l seed --description 'Start with a given random number seed.'
complete -c gazebo -l iters --description 'Number of iterations to simulate.'
complete -c gazebo -l minimal_comms --description 'Reduce the TCP/IP traffic output by gazebo.'
complete -c gazebo -s g -l gui-plugin --description 'Load a GUI plugin.'
complete -c gazebo -s s -l server-plugin --description 'Load a server plugin.'

