# gdnsdomainname
# Autogenerated from man page /usr/local/Cellar/inetutils/1.9.4_1/share/man/man1/gdnsdomainname.1
complete -c gdnsdomainname -s '?' -l help --description 'give this help list.'
complete -c gdnsdomainname -l usage --description 'give a short usage message.'
complete -c gdnsdomainname -s V -l version --description 'print program version AUTHOR Written by Simon Josefsson.'

