# gengraph
# Autogenerated from man page /usr/share/man/man1/gengraph.1.gz
# using Deroffing man parser
complete -c gengraph -s h -l help: --description '.'
complete -c gengraph -s V -l version: --description '.'
complete -c gengraph -s D -l dot: --description '.'
complete -c gengraph -s d -l depth: --description '.'
complete -c gengraph -s i -l ignore: --description '.'
complete -c gengraph -s l -l location: --description '.'
complete -c gengraph -s s -l show: --description 'USAGE gengraph -i "exit strlen" nccout main | d… [See Man Page]'

