# getconfigvalues
# Autogenerated from man page /usr/share/man/man1/getconfigvalues.1
# using Deroffing man parser
complete -c getconfigvalues -s H -l help --description 'Prints this help page.'
complete -c getconfigvalues -s V -l version --description 'Prints the name and version number of this program.'
complete -c getconfigvalues -s c -l check --description 'This program uses the local XML database to obt… [See Man Page]'

