# getfilehash
# Autogenerated from man page /usr/share/man/man8/getfilehash.8
# using Deroffing man parser
complete -c getfilehash -s H -l help --description 'Prints this help command.'
complete -c getfilehash -s V --description 'Prints the version information for this program… [See Man Page]'

