# ghwdump
# Autogenerated from man page /usr/share/man/man1/ghwdump.1.gz
# using Type1
complete -c ghwdump -s t --description 'Display types.'
complete -c ghwdump -s h --description 'Display hierarchy.'
complete -c ghwdump -s T --description 'Display time.'
complete -c ghwdump -s s --description 'Display signals (and time).'
complete -c ghwdump -s l --description 'Display list of sections.'

