# git-lfs-pointer
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-pointer.1
complete -c git-lfs-pointer -l file --description 'A local file to build the pointer from.'
complete -c git-lfs-pointer -l pointer --description 'A local file including the contents of a pointer generated from another imple…'

