# git-lfs-update
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-update.1
complete -c git-lfs-update -l manual -s m --description '.'
complete -c git-lfs-update -l force -s f --description '.'

