# git-lfs-filter-process
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-filter-process.1
complete -c git-lfs-filter-process -l skip --description 'Skip automatic downloading of objects on clone or pull.'

