# git-lfs-track
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-track.1
complete -c git-lfs-track -l verbose -s v --description '.'
complete -c git-lfs-track -l dry-run -s d --description '.'
complete -c git-lfs-track -l lockable -s l --description '.'
complete -c git-lfs-track -l not-lockable --description '.'
complete -c git-lfs-track -l no-modify-attrs --description '.'

