# git-lfs-locks
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-locks.1
complete -c git-lfs-locks -s r -l remote --description 'Specify the Git LFS server to use.  Ignored if the lfs. url config key is set.'
complete -c git-lfs-locks -s i -l id --description 'Specifies a lock by its ID.  Returns a single result.'
complete -c git-lfs-locks -s p -l path --description 'Specifies a lock by its path.  Returns a single result.'
complete -c git-lfs-locks -l local --description 'Lists only the locks cached locally.  Skips a remote call.'
complete -c git-lfs-locks -s l -l limit --description 'Specifies number of results to return.'

