# git-lfs-migrate
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-migrate.1
complete -c git-lfs-migrate -s I -l include --description 'See INCLUDE AND EXCLUDE.'
complete -c git-lfs-migrate -s X -l exclude --description 'See INCLUDE AND EXCLUDE.'
complete -c git-lfs-migrate -l include-ref --description 'See [INCLUDE AND EXCLUDE (REFS)].'
complete -c git-lfs-migrate -l exclude-ref --description 'See [INCLUDE AND EXCLUDE (REFS)].'
complete -c git-lfs-migrate -l skip-fetch --description 'Assumes that the known set of remote references is complete, and should not b…'
complete -c git-lfs-migrate -l everything --description 'See [INCLUDE AND EXCLUDE (REFS)].'

