# git-lfs-uninstall
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-uninstall.1
complete -c git-lfs-uninstall -l local --description 'Removes the "lfs" smudge and clean filters from the local repository\'s git co…'

