# git-lfs-clone
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-clone.1
complete -c git-lfs-clone -s I -l include --description 'See INCLUDE AND EXCLUDE .'
complete -c git-lfs-clone -s X -l exclude --description 'See INCLUDE AND EXCLUDE .'

