# git-lfs-unlock
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-unlock.1
complete -c git-lfs-unlock -s r -l remote --description 'Specify the Git LFS server to use.  Ignored if the lfs. url config key is set.'
complete -c git-lfs-unlock -s f -l force --description 'Tells the server to remove the lock, even if it\'s owned by another user.'
complete -c git-lfs-unlock -s i -l id --description 'Specifies a lock by its ID instead of path.'

