# git-lfs-fetch
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-fetch.1
complete -c git-lfs-fetch -s I -l include --description 'Specify lfs. fetchinclude just for this invocation; see INCLUDE AND EXCLUDE .'
complete -c git-lfs-fetch -s X -l exclude --description 'Specify lfs. fetchexclude just for this invocation; see INCLUDE AND EXCLUDE .'
complete -c git-lfs-fetch -l recent --description 'Download objects referenced by recent branches & commits in addition to those…'
complete -c git-lfs-fetch -l all --description 'Download all objects referenced by any commit that is reachable; this is prim…'

