# git-lfs-push
# Autogenerated from man page /usr/local/share/man/man1/git-lfs-push.1
complete -c git-lfs-push -l dry-run --description 'Print the files that would be pushed, without actually pushing them.'
complete -c git-lfs-push -l all --description 'This pushes all objects to the remote that are referenced by any commit reach…'

