# glmark2
# Autogenerated from man page /usr/share/man/man1/glmark2.1.gz
# using Deroffing man parser
complete -c glmark2 -s b -l benchmark --description 'A benchmark to run: \'scene(:opt1=val1)*\' (the o… [See Man Page]'
complete -c glmark2 -s f -l benchmark-file --description 'Load benchmarks to run from a file containing a… [See Man Page]'
complete -c glmark2 -l validate --description 'Run a quick output validation test instead of r… [See Man Page]'
complete -c glmark2 -l frame-end --description 'How to end a frame [default,none,swap,finish,readpixels].'
complete -c glmark2 -l off-screen --description 'Render to an off-screen surface.'
complete -c glmark2 -l visual-config --description 'The visual configuration to use for the renderi… [See Man Page]'
complete -c glmark2 -l reuse-context --description 'Use a single context for all scenes (by default… [See Man Page]'
complete -c glmark2 -s s -l size --description 'Size of the output window (default: 800x600).'
complete -c glmark2 -l fullscreen --description 'Run in fullscreen mode (equivalent to --size -1x-1).'
complete -c glmark2 -s l -l list-scenes --description 'Display information about the available scenes … [See Man Page]'
complete -c glmark2 -l show-all-options --description 'Show all scene option values used for benchmark… [See Man Page]'
complete -c glmark2 -l run-forever --description 'Run indefinitely, looping from the last benchma… [See Man Page]'
complete -c glmark2 -l annotate --description 'Annotate the benchmarks with on-screen informat… [See Man Page]'
complete -c glmark2 -s d -l debug --description 'Display debug messages.'
complete -c glmark2 -s h -l help --description 'Display help BENCHMARKS glmark2 offers a suite … [See Man Page]'
complete -c glmark2 -l 'list-scenes).' --description '.'

