# gnome-mahjongg
# Autogenerated from man page /usr/share/man/man6/gnome-mahjongg.6.gz
# using Deroffing man parser
complete -c gnome-mahjongg -s v -l version --description 'Print release version and exit.'

