# gnome-mines
# Autogenerated from man page /usr/share/man/man6/gnome-mines.6.gz
# using Deroffing man parser
complete -c gnome-mines -s v -l version --description 'Print release version and exit.'
complete -c gnome-mines -l small --description '.'
complete -c gnome-mines -l medium --description '.'
complete -c gnome-mines -l big --description '.'

