# gnucap-ibis
# Autogenerated from man page /usr/share/man/man1/gnucap-ibis.1.gz
# using Deroffing man parser
complete -c gnucap-ibis -l typ --description 'sets simulation mode to typical values (default).'
complete -c gnucap-ibis -l min --description 'sets simulation mode to minimal values.'
complete -c gnucap-ibis -l max --description 'sets simulation mode to maximal values.'
complete -c gnucap-ibis -l power-on --description 'sets device state to power on.'
complete -c gnucap-ibis -l on --description 'sets device state to on.'
complete -c gnucap-ibis -l off --description 'sets device state to off.'
complete -c gnucap-ibis -l prefix --description 'sets the prefix on generated code (default no prefix).'
complete -c gnucap-ibis -l dump --description 'enable the dumping of the interprented IBIS fil… [See Man Page]'
complete -c gnucap-ibis -l spice --description 'enable the dumping of a SPICE model.'

