# gnucap
# Autogenerated from man page /usr/share/man/man1/gnucap.1.gz
# using Deroffing man parser
complete -c gnucap -s b --description 'execute the commands in the named file then exit (batch mode).'
complete -c gnucap -s i --description 'execute the commands in the named file then go … [See Man Page]'

