# gnuplot5
# Autogenerated from man page /usr/share/man/man1/gnuplot5.1.gz
# using Deroffing man parser
complete -c gnuplot5 -s p -l persist --description '.'
complete -c gnuplot5 -s c --description '.'
complete -c gnuplot5 -s d -l default --description '.'
complete -c gnuplot5 -s e --description '.'
complete -c gnuplot5 -s h -l help --description '.'
complete -c gnuplot5 -s V --description 'X11 OPTIONS For terminal type x11, gnuplot acce… [See Man Page]'

