# gnuplot4
# Autogenerated from man page /usr/share/man/man1/gnuplot4.1.gz
# using Deroffing man parser
complete -c gnuplot4 -s p -l persist --description '.'
complete -c gnuplot4 -s d -l default --description '.'
complete -c gnuplot4 -s e --description '.'
complete -c gnuplot4 -s h -l help --description '.'
complete -c gnuplot4 -s V --description 'X11 OPTIONS Gnuplot provides the x11 terminal t… [See Man Page]'

