# gnuplot5-qt
# Autogenerated from man page /usr/share/man/man1/gnuplot5-qt.1.gz
# using Deroffing man parser
complete -c gnuplot5-qt -s p -l persist --description '.'
complete -c gnuplot5-qt -s c --description '.'
complete -c gnuplot5-qt -s d -l default --description '.'
complete -c gnuplot5-qt -s e --description '.'
complete -c gnuplot5-qt -s h -l help --description '.'
complete -c gnuplot5-qt -s V --description 'X11 OPTIONS For terminal type x11, gnuplot acce… [See Man Page]'

