# gnuplot
# Autogenerated from man page /usr/share/man/man1/gnuplot.1.gz
# using Deroffing man parser
complete -c gnuplot -s p -l persist --description '.'
complete -c gnuplot -s c --description '.'
complete -c gnuplot -s d -l default --description '.'
complete -c gnuplot -s e --description '.'
complete -c gnuplot -s h -l help --description '.'
complete -c gnuplot -s V --description 'X11 OPTIONS For terminal type x11, gnuplot acce… [See Man Page]'

