# gp-2
# Autogenerated from man page /usr/share/man/man1/gp-2.7.1.gz
# using Deroffing man parser
complete -c gp-2 -s f -l fast --description 'Fast start (or factory settings).  Do not read  .'
complete -c gp-2 -s p --description '[DEPRECATED] Upon startup, gp computes a table … [See Man Page]'
complete -c gp-2 -s q -l quiet --description 'Quiet mode.'
complete -c gp-2 -s D -l default --description 'performs  default(key,  val) ";" on startup, ov… [See Man Page]'
complete -c gp-2 -s s --description 'Size of gp internal stack allocated on startup.'
complete -c gp-2 -l emacs --description 'gp can be run in an  Emacs shell (see GP User\'s… [See Man Page]'
complete -c gp-2 -l help --description 'print a summary of available command-line options.'
complete -c gp-2 -l test --description 'run gp in test mode: suppress printing of histo… [See Man Page]'
complete -c gp-2 -l texmacs --description 'gp can be run from a  TeXmacs frontend.'
complete -c gp-2 -l version --description 'output version info (banner) then exit.'
complete -c gp-2 -l version-short --description 'output version number then exit.'

