# gp2c
# Autogenerated from man page /usr/share/man/man1/gp2c.1.gz
# using Deroffing man parser
complete -c gp2c -s o --description '.'
complete -c gp2c -s g --description '.'
complete -c gp2c -o iN: --description '.'
complete -c gp2c -s W --description '.'
complete -c gp2c -s C --description '.'
complete -c gp2c -s L --description '.'
complete -c gp2c -s p --description '.'
complete -c gp2c -s s --description '.'
complete -c gp2c -o S: --description 'query options:.'
complete -c gp2c -s h --description '.'
complete -c gp2c -s f --description '.'
complete -c gp2c -s l --description '.'
complete -c gp2c -s t --description '.'
complete -c gp2c -s v --description 'debugging options:.'
complete -c gp2c -s d --description '.'
complete -c gp2c -s y --description '.'
complete -c gp2c -s T --description '.'
complete -c gp2c -o TT --description '.'
complete -c gp2c -s G --description '.'
complete -c gp2c -s V --description '.'

