# gphelp
# Autogenerated from man page /usr/share/man/man1/gphelp.1.gz
# using Deroffing man parser
complete -c gphelp -o cb -o color_bold --description 'color used for bold.  See  -color_help .'
complete -c gphelp -o ch -o color_help --description 'color (between 1 and 16) used for general printing.'
complete -c gphelp -o cu -o color_underline --description 'color used for underline.  See  -color_help .'
complete -c gphelp -o detex --description 'Use  detex mode.'
complete -c gphelp -s k --description 'Switch to  apropos mode.'
complete -c gphelp -o raw --description 'use internal format for output (using @x markers).'
complete -c gphelp -o to_pod --description 'try to convert file from TeX to POD format.'

