# gssd
# Autogenerated from man page /usr/share/man/man8/gssd.8.gz
# using Deroffing man parser
complete -c gssd -s D --description 'DNS Reverse lookups are not used for determinin… [See Man Page]'
complete -c gssd -s f --description 'Runs  rpc.'
complete -c gssd -s n --description 'When specified, UID 0 is forced to obtain user … [See Man Page]'
complete -c gssd -s k --description 'Tells  rpc.'
complete -c gssd -s l --description 'When specified, restricts  rpc.'
complete -c gssd -s p --description 'Tells  rpc. gssd where to look for the rpc_pipefs filesystem.'
complete -c gssd -s d --description 'This option specifies a colon separated list of… [See Man Page]'
complete -c gssd -s M --description 'By default, machine credentials are stored in f… [See Man Page]'
complete -c gssd -s v --description 'Increases the verbosity of the output (can be s… [See Man Page]'
complete -c gssd -s r --description 'If the RPCSEC_GSS library supports setting debu… [See Man Page]'
complete -c gssd -s R --description 'Kerberos tickets from this  realm will be prefe… [See Man Page]'
complete -c gssd -s t --description 'Timeout, in seconds, for kernel GSS contexts.'
complete -c gssd -s e --description 'Return EACCESS instead of EKEYEXPIRED when a us… [See Man Page]'

