# gtkdocize
# Autogenerated from man page /usr/share/man/man1/gtkdocize.1.gz
# using Type1
complete -c gtkdocize -l help --description 'print a short help and exit.'
complete -c gtkdocize -l version --description 'print version information and exit.'
complete -c gtkdocize -l copy --description 'copy files instead of making symlinks.'

