# gtscheck
# Autogenerated from man page /usr/share/man/man1/gtscheck.1.gz
# using Deroffing man parser
complete -c gtscheck -s v -l verbose --description 'Print statistics about the surface.'
complete -c gtscheck -s h -l help --description 'Display the help and exit.'

