# gzclient
# Autogenerated from man page /usr/share/man/man1/gzclient.1.gz
# using Type1
complete -c gzclient -s v -l version --description 'Output version information.'
complete -c gzclient -l verbose --description 'Increase the messages written to the terminal.'
complete -c gzclient -s h -l help --description 'Produce this help message.'

