# hex2hcd
# Autogenerated from man page /usr/share/man/man1/hex2hcd.1.gz
# using Deroffing man parser
complete -c hex2hcd -s o -l output --description 'Provide firmware output file.'
complete -c hex2hcd -s h -l help --description 'Show help options SEE ALSO The full documentati… [See Man Page]'

