# hp-config_usb_printer
# Autogenerated from man page /usr/share/man/man1/hp-config_usb_printer.1.gz
# using Deroffing man parser
complete -c hp-config_usb_printer -o 'l<level>' -l logging --description '<level>: none, info*, error, warn, debug (*defa… [See Man Page]'
complete -c hp-config_usb_printer -s g -o 'ldebug)' --description 'This help information:.'
complete -c hp-config_usb_printer -s h -l help --description 'USB BUSDEVICE USB bus:device : "xxx:yyy" where … [See Man Page]'

