# idle3
# Autogenerated from man page /usr/share/man/man1/idle3.1.gz
# using Deroffing man parser
complete -c idle3 -s h --description 'PD Print this help message and exit.'
complete -c idle3 -s n --description 'PD Run IDLE without a subprocess (see Help/IDLE… [See Man Page]'
complete -c idle3 -s e --description 'PD Open an edit window.'
complete -c idle3 -s i --description 'PD Open a shell window.'
complete -c idle3 -s c --description 'PD Run the command in a shell, or.'
complete -c idle3 -s r --description 'PD Run script from file. PP.'
complete -c idle3 -s d --description 'PD Enable the debugger.'
complete -c idle3 -s s --description 'PD Run $IDLESTARTUP or $PYTHONSTARTUP before anything else.'
complete -c idle3 -s t --description '.'

