# idle3ctl
# Autogenerated from man page /usr/share/man/man8/idle3ctl.8.gz
# using Deroffing man parser
complete -c idle3ctl -s h --description 'Display help.'
complete -c idle3ctl -s V --description 'Show version and exit.'
complete -c idle3ctl -s v --description 'activate verbose output, mainly useful for debugging.'
complete -c idle3ctl -l force --description 'force execution even if no Western Digital HDD are detected.'
complete -c idle3ctl -s g --description 'get raw idle3 timer value.'
complete -c idle3ctl -o g100 --description 'get idle3 timer value as wdidle3 v1. 00 would display it.'
complete -c idle3ctl -o g103 --description 'get idle3 timer value as wdidle3 v1. 03 would display it.'
complete -c idle3ctl -s d --description 'disable idle3 timer.'
complete -c idle3ctl -o 's<value>' --description 'set idle3 timer raw value.'

