# idmapd
# Autogenerated from man page /usr/share/man/man8/idmapd.8.gz
# using Darwin man parser
complete -c idmapd -s v --description 'Increases the verbosity level (can be specified… [See Man Page]'
complete -c idmapd -s f --description 'Runs idmapd in the foreground and prints all ou… [See Man Page]'
complete -c idmapd -s d --description 'Set domain to domain.'
complete -c idmapd -s p --description 'Specifies the location of the RPC pipefs to be path.'
complete -c idmapd -s U --description 'Specifies the NFSv4 nobody user to be username.'
complete -c idmapd -s G --description 'Specifies the NFSv4 nobody group to be groupname.'
complete -c idmapd -s c --description 'Use configuration file path.'
complete -c idmapd -s C --description 'Client-only: perform no idmapping for any NFS s… [See Man Page]'
complete -c idmapd -s S --description 'Server-only: perform no idmapping for any NFS c… [See Man Page]'

