# iex
# Autogenerated from man page /usr/share/man/man1/iex.1.gz
# using Darwin man parser
complete -c iex -s e --description 'Evaluates the specified expression.'
complete -c iex -s r --description 'Requires the specified file.'
complete -c iex -s S --description 'Runs the specified script.'
complete -c iex -o pa --description 'Adds the specified directory to the beginning of the code path.'
complete -c iex -o pr --description 'Does the same thing as r see above but in parallel.'
complete -c iex -o pz --description 'Adds the specified directory to the end of the code path.'
complete -c iex -l app --description 'Starts the specified application and all its dependencies.'
complete -c iex -l erl --description 'Serves the same purpose as ELIXIR_ERL_OPTIONS s… [See Man Page]'
complete -c iex -l cookie --description 'Specifies the magic cookie value.'
complete -c iex -l detached --description 'Runs the Erlang runtime system detached from th… [See Man Page]'
complete -c iex -l hidden --description 'Starts a hidden node.'
complete -c iex -l sname --description 'Gives a node a short name and starts it.'
complete -c iex -l name --description 'Gives a node a long name and starts it.'
complete -c iex -l dot-iex --description 'Loads the specified file instead of . iex.'
complete -c iex -l remsh --description 'Connects to the specified node which was starte… [See Man Page]'

