# imgsize
# Autogenerated from man page /usr/share/man/man1/imgsize.1p.gz
# using Type1
complete -c imgsize -s r --description 'el.'
complete -c imgsize -s a --description 'el.'
complete -c imgsize -s f --description 'el.'

