# installwatch
# Autogenerated from man page /usr/share/man/man1/installwatch.1.gz
# using Type1
complete -c installwatch -s o -l logfile --description 'Directs that output from the logged command be … [See Man Page]'
complete -c installwatch -s r -l root --description 'Sets the directory under which meta-info and tr… [See Man Page]'
complete -c installwatch -s t -l trans --description 'Toggle translation capabilities.'
complete -c installwatch -s e -l exclude --description 'Sets a comma separated neutral directory list, … [See Man Page]'
complete -c installwatch -s d -l dbgfile --description 'Specify a debug file.'
complete -c installwatch -s v -l dbglvl --description 'Sets the debug level to be used.'

