# intel_infoframes
# Autogenerated from man page /usr/share/man/man1/intel_infoframes.1.gz
# using Deroffing man parser
complete -c intel_infoframes -s h --description 'or.'
complete -c intel_infoframes -l help --description 'options to learn how to use the command LIMITAT… [See Man Page]'

