# intel_panel_fitter
# Autogenerated from man page /usr/share/man/man1/intel_panel_fitter.1.gz
# using Deroffing man parser
complete -c intel_panel_fitter -s p --description 'pipe to be used (A, B or C, but C is only prese… [See Man Page]'
complete -c intel_panel_fitter -s x --description 'final screen width size in pixels (needs -p option).'
complete -c intel_panel_fitter -s y --description 'final screen height size in pixels (needs -p option).'
complete -c intel_panel_fitter -s d --description 'disable panel fitter (needs -p option, ignores … [See Man Page]'
complete -c intel_panel_fitter -s l --description 'list current state of each pipe.'
complete -c intel_panel_fitter -s h --description 'prints the help message.'

