# ip-link
# Autogenerated from man page /usr/share/man/man8/ip-link.8.gz
# using Deroffing man parser
complete -c ip-link -o 'V[ersion]' --description '.'
complete -c ip-link -o 'h[uman-readable]' --description '.'
complete -c ip-link -o 's[tatistics]' --description '.'
complete -c ip-link -o 'r[esolve]' --description '.'
complete -c ip-link -o 'f[amily]' --description 'inet  |  inet6  |  ipx  |  dnet  |  link  } | .'
complete -c ip-link -o 'o[neline]' --description '.'
complete -c ip-link -o 'br[ief]' --description 'ip link add [  link DEVICE  ] [  name  ] NAME.'
complete -c ip-link -s t -s A -s j -l set-class --description 'and this "4" priority can be used in the egress… [See Man Page]'
complete -c ip-link -s s -o stats -o statistics --description 'output more statistics about packet usage.'
complete -c ip-link -s d -o details --description 'output more detailed information.'
complete -c ip-link -s h -o human -o human-readable --description 'output statistics with human readable values nu… [See Man Page]'
complete -c ip-link -o iec --description 'print human readable rates in IEC units (ie.  1K = 1024).'

