# jmol
# Autogenerated from man page /usr/share/man/man1/jmol.1.gz
# using Type1
complete -c jmol -s h -l help --description 'Print help on the command line options.'
complete -c jmol -s g -l geometry --description 'Use window-geometry WIDTH x HEIGHT.'
complete -c jmol -s s -l script --description 'Run script scriptfile.'
complete -c jmol -s D --description 'Use value for the given property (for a list see below).'
complete -c jmol -o 'Dcdk.debugging' --description 'Set debugging (default: false).'
complete -c jmol -o 'Dcdk.debug.stdout' --description 'Set debug to stdout (default: false).'
complete -c jmol -o 'Duser.language' --description 'Set user language (default: EN).'
complete -c jmol -o 'Ddisplay.speed' --description 'Set display speed in milli seconds (ms) or fram… [See Man Page]'
complete -c jmol -o DJmolConsole --description 'Start with Jmol-console (default: true).'

