# jscal
# Autogenerated from man page /usr/share/man/man1/jscal.1.gz
# using Deroffing man parser
complete -c jscal -s c -l calibrate --description 'Calibrate the joystick.'
complete -c jscal -s h -l help --description 'Print out a summary of available options.'
complete -c jscal -s s -l set-correction --description 'Sets correction to specified values.'
complete -c jscal -s u -l set-mappings --description 'Sets axis and button mappings.'
complete -c jscal -s t -l test-center --description 'Tests if the joystick is correctly calibrated.'
complete -c jscal -s V -l version --description 'Prints the version numbers of the running joyst… [See Man Page]'
complete -c jscal -s p -l print-correction --description 'Prints the current correction settings.'
complete -c jscal -s q -l print-mappings --description 'Prints the current axis and button mappings.'

