# jstest
# Autogenerated from man page /usr/share/man/man1/jstest.1.gz
# using Deroffing man parser
complete -c jstest -l normal --description 'One-line mode showing immediate status.'
complete -c jstest -l old --description 'Same as --normal, using 0. x interface.'
complete -c jstest -l event --description 'Prints events as they come in.'
complete -c jstest -l nonblock --description 'Same as --event, in nonblocking mode.'
complete -c jstest -l select --description 'Same as --event, using select(2) call.'

