# kate
# Autogenerated from man page /usr/share/man/man1/kate.1.gz
# using Deroffing man parser
complete -c kate -s s -l start --description 'Start Kate with a given session.'
complete -c kate -l startanon --description 'Start Kate with a new anonymous session, implies -n.'
complete -c kate -s n -l new --description 'Force start of a new Kate instance (is ignored … [See Man Page]'
complete -c kate -s b -l block --description 'If using an already running Kate instance, bloc… [See Man Page]'
complete -c kate -s p -l pid --description 'Only try to reuse kate instance with this pid (… [See Man Page]'
complete -c kate -s e -l encoding --description 'Set encoding for the file to open .'
complete -c kate -s l -l line --description 'Navigate to this line.'
complete -c kate -s c -l column --description 'Navigate to this column.'
complete -c kate -s i -l stdin --description 'Read the contents of stdin.'
complete -c kate -l tempfile --description 'The files/URLs opened by the application will b… [See Man Page]'
complete -c kate -s h -l help --description 'This lists the options available at the command line.'
complete -c kate -l author --description 'Lists Kate\\*(Aqs authors in the terminal window.'
complete -c kate -s v -l version --description 'Lists version information for Kate.'
complete -c kate -l license --description 'Shows license information.'
complete -c kate -o 'n.' --description '.'

