# kile
# Autogenerated from man page /usr/share/man/man1/kile.1.gz
# using Deroffing man parser
complete -c kile -l line --description 'Jump to the given line in the file that is opened.'
complete -c kile -l new --description 'Start a new Kile main window.'

