# kwallet-query
# Autogenerated from man page /usr/share/man/man1/kwallet-query.1.gz
# using Deroffing man parser
complete -c kwallet-query -s h -l help --description 'Display a short help message.'
complete -c kwallet-query -s l -l list-entries --description 'List password entries.'
complete -c kwallet-query -s r -l read-password --description 'Read the contents of the given Entry from the F… [See Man Page]'
complete -c kwallet-query -s w -l write-password --description 'Write secrets to the given Entry under the Fold… [See Man Page]'
complete -c kwallet-query -s f -l folder --description 'Set the wallet folder to Folder value.'
complete -c kwallet-query -s v -l verbose --description 'Output more information when performing the ope… [See Man Page]'

