# latexdiff-svn
# Autogenerated from man page /usr/share/man/man1/latexdiff-svn.1.gz
# using Type1
complete -c latexdiff-svn -l rcs -l svn -l cvs -l git -l hg --description 'Set the version system.'
complete -c latexdiff-svn -s r -s r -l revision -l revision --description 'Choose revision (under \\s-1RCS, CVS, SVN, GIT\\s0 or \\s-1HG\\s0).'
complete -c latexdiff-svn -s d -l dir -s d -l dir --description 'Rather than appending the string \\f(CW\\*(C`diff… [See Man Page]'
complete -c latexdiff-svn -l flatten -l flatten --description 'If combined with \\f(CW\\*(C`--git\\*(C\', \\f(CW\\*(… [See Man Page]'
complete -c latexdiff-svn -l fast -l so --description 'Use \\f(CW\\*(C`latexdiff-fast\\*(C\' or \\f(CW\\*(C`… [See Man Page]'
complete -c latexdiff-svn -l ps -l postscript --description 'Generate postscript output from difference file.'
complete -c latexdiff-svn -l pdf --description 'Generate pdf output from difference file using … [See Man Page]'
complete -c latexdiff-svn -l only-changes --description 'Post-process the output such that only pages wi… [See Man Page]'
complete -c latexdiff-svn -l force --description 'Overwrite existing diff files without asking for confirmation.'
complete -c latexdiff-svn -l help -s h --description 'Show help text.'

