# lftpget
# Autogenerated from man page /usr/local/share/man/man1/lftpget.1
complete -c lftpget -s c --description 'Continue a previous download.'
complete -c lftpget -s d --description 'Debug output.'

