# lgrind
# Autogenerated from man page /usr/share/man/man1/lgrind.1.gz
# using Deroffing man parser
complete -c lgrind -s e --description 'process a LaTeX file for embedded code.'
complete -c lgrind -s i --description 'process source code file for inclusion in a LaTeX document.'
complete -c lgrind -s n --description 'don\'t boldface keywords.'
complete -c lgrind -s c --description 'don\'t treat @, etc.  specially in comments.'
complete -c lgrind -s t --description 'change tab width (default 8).'
complete -c lgrind -s h --description 'specifies text to go into the header.'
complete -c lgrind -s d --description 'specifies the language definitions file (defaul… [See Man Page]'
complete -c lgrind -o 'd!' --description 'same as above, but write patched executable.'
complete -c lgrind -s l --description 'specifies the language to use.'
complete -c lgrind -s s --description 'shows a list of currently known languages.'

