# libesmtp-config
# Autogenerated from man page /usr/share/man/man1/libesmtp-config.1.gz
# using Deroffing man parser
complete -c libesmtp-config -l prefix --description 'change libesmtp prefix [default /usr].'
complete -c libesmtp-config -l libs --description 'print library linking information.'
complete -c libesmtp-config -l cflags --description 'print pre-processor and compiler flags.'
complete -c libesmtp-config -l plugindir --description 'print authentication plugin location.'
complete -c libesmtp-config -l help --description 'display this help and exit.'
complete -c libesmtp-config -l version --description 'output version information.'

