# libftdi-config
# Autogenerated from man page /usr/share/man/man1/libftdi-config.1.gz
# using Deroffing man parser
complete -c libftdi-config -l version --description 'Print the currently installed version of libftd… [See Man Page]'
complete -c libftdi-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c libftdi-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c libftdi-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c libftdi-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

