# libmcrypt-config
# Autogenerated from man page /usr/share/man/man1/libmcrypt-config.1.gz
# using Type1
complete -c libmcrypt-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c libmcrypt-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c libmcrypt-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c libmcrypt-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'

