# lit-3
# Autogenerated from man page /usr/share/man/man1/lit-3.8.1.gz
# using Deroffing man parser
complete -c lit-3 -s a -l show-all --description 'Show more information about all tests, for exam… [See Man Page]'

