# lldb-mi-4
# Autogenerated from man page /usr/share/man/man1/lldb-mi-4.0.1.gz
# using Deroffing man parser
complete -c lldb-mi-4 -s h --description '.'
complete -c lldb-mi-4 -l help --description 'Prints out usage information for the MI debugger.'
complete -c lldb-mi-4 -l version --description 'Prints out GNU (gdb) version information.'
complete -c lldb-mi-4 -l versionLong --description 'Prints out MI Driver version information.'
complete -c lldb-mi-4 -l interpreter --description 'This option is kept for backward compatibility.'
complete -c lldb-mi-4 -s s --description '.'
complete -c lldb-mi-4 -l source --description 'Tells the debugger to read in and execute the l… [See Man Page]'
complete -c lldb-mi-4 -l executable --description 'Use the MI Driver in MI mode for the debugging … [See Man Page]'
complete -c lldb-mi-4 -l log --description 'Use this argument to tell the MI Driver to upda… [See Man Page]'
complete -c lldb-mi-4 -l log-dir --description 'Use this argument to specify the directory the … [See Man Page]'

