# llvm-link-4
# Autogenerated from man page /usr/share/man/man1/llvm-link-4.0.1.gz
# using Deroffing man parser
complete -c llvm-link-4 -s f --description 'Enable binary output on terminals.'
complete -c llvm-link-4 -s o --description 'Specify the output file name.'
complete -c llvm-link-4 -s S --description 'Write output in LLVM intermediate language (ins… [See Man Page]'
complete -c llvm-link-4 -s d --description 'If specified, llvm-link prints a human-readable… [See Man Page]'
complete -c llvm-link-4 -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c llvm-link-4 -s v --description 'Verbose mode.'

