# llvm-profdata-3
# Autogenerated from man page /usr/share/man/man1/llvm-profdata-3.8.1.gz
# using Deroffing man parser
complete -c llvm-profdata-3 -o weighted-input --description 'Specify an input file name along with a weight.'

