# llvm-symbolizer-3
# Autogenerated from man page /usr/share/man/man1/llvm-symbolizer-3.8.1.gz
# using Deroffing man parser
complete -c llvm-symbolizer-3 -o print-address --description 'Print address before the source code location.'
complete -c llvm-symbolizer-3 -o pretty-print --description 'Print human readable output.'

