# llvm-symbolizer-4
# Autogenerated from man page /usr/share/man/man1/llvm-symbolizer-4.0.1.gz
# using Deroffing man parser
complete -c llvm-symbolizer-4 -o obj --description 'Path to object file to be symbolized. UNINDENT NDENT 0. 0.'
complete -c llvm-symbolizer-4 -o functions --description 'Specify the way function names are printed (omi… [See Man Page]'
complete -c llvm-symbolizer-4 -o use-symbol-table --description 'Prefer function names stored in symbol table to… [See Man Page]'
complete -c llvm-symbolizer-4 -o demangle --description 'Print demangled function names.  Defaults to true.'
complete -c llvm-symbolizer-4 -o inlining --description 'If a source code location is in an inlined func… [See Man Page]'
complete -c llvm-symbolizer-4 -o default-arch --description 'If a binary contains object files for multiple … [See Man Page]'
complete -c llvm-symbolizer-4 -o dsym-hint --description '(Darwin-only flag).'
complete -c llvm-symbolizer-4 -o print-address --description 'Print address before the source code location.'
complete -c llvm-symbolizer-4 -o pretty-print --description 'Print human readable output.'

