# llvm-dwarfdump-3
# Autogenerated from man page /usr/share/man/man1/llvm-dwarfdump-3.8.1.gz
# using Deroffing man parser
complete -c llvm-dwarfdump-3 -o filter-print-funcs --description '.'
complete -c llvm-dwarfdump-3 -o merror-missing-parenthesis --description '.'
complete -c llvm-dwarfdump-3 -o merror-noncontigious-register --description '.'
complete -c llvm-dwarfdump-3 -o mfuture-regs --description '.'
complete -c llvm-dwarfdump-3 -o mno-compound --description '.'
complete -c llvm-dwarfdump-3 -o mno-pairing --description '.'
complete -c llvm-dwarfdump-3 -o mwarn-missing-parenthesis --description '.'
complete -c llvm-dwarfdump-3 -o mwarn-noncontigious-register --description '.'
complete -c llvm-dwarfdump-3 -o mwarn-sign-mismatch --description '.'
complete -c llvm-dwarfdump-3 -o rdf-dump --description '.'
complete -c llvm-dwarfdump-3 -o rdf-limit --description '.'
complete -c llvm-dwarfdump-3 -o sample-profile-check-record-coverage --description '.'
complete -c llvm-dwarfdump-3 -o sample-profile-check-sample-coverage --description '.'
complete -c llvm-dwarfdump-3 -o sample-profile-global-cold-threshold --description '.'
complete -c llvm-dwarfdump-3 -o sample-profile-global-hot-threshold --description '.'
complete -c llvm-dwarfdump-3 -o sample-profile-inline-hot-threshold --description '.'
complete -c llvm-dwarfdump-3 -o summary-file --description '.'

