# llvm-profdata-4
# Autogenerated from man page /usr/share/man/man1/llvm-profdata-4.0.1.gz
# using Deroffing man parser
complete -c llvm-profdata-4 -o help --description 'Print a summary of command line options.'
complete -c llvm-profdata-4 -o output -s o --description 'Specify the output file name.'
complete -c llvm-profdata-4 -o weighted-input --description 'Specify an input file name along with a weight.'
complete -c llvm-profdata-4 -o input-files -s f --description 'Specify a file which contains a list of files to merge.'
complete -c llvm-profdata-4 -o instr --description 'Specify that the input profile is an instrument… [See Man Page]'
complete -c llvm-profdata-4 -o sample --description 'Specify that the input profile is a sample-based profile.'
complete -c llvm-profdata-4 -o binary --description 'Emit the profile using a binary encoding.'
complete -c llvm-profdata-4 -o text --description 'Emit the profile in text mode.'
complete -c llvm-profdata-4 -o gcc --description 'Emit the profile using GCC\'s gcov format (Not yet supported).'
complete -c llvm-profdata-4 -o 'sparse[' --description 'Do not emit function records with 0 execution count.'
complete -c llvm-profdata-4 -o num-threads -s j --description 'Use N threads to perform profile merging.'
complete -c llvm-profdata-4 -o all-functions --description 'Print details for every function.'
complete -c llvm-profdata-4 -o counts --description 'Print the counter values for the displayed functions.'
complete -c llvm-profdata-4 -o function --description 'Print details for a function if the function\'s … [See Man Page]'

