# lnsysconfigd
# Autogenerated from man page /usr/share/man/man8/lnsysconfigd.8
# using Deroffing man parser
complete -c lnsysconfigd -s H -l help --description 'Prints this help command.'
complete -c lnsysconfigd -s V --description 'Prints the version information for this program.'
complete -c lnsysconfigd -s b -l foreground --description 'Run this daemon in the foreground for debugging purposes.'

