# lsinitrd
# Autogenerated from man page /usr/share/man/man1/lsinitrd.1.gz
# using Deroffing man parser
complete -c lsinitrd -s h -l help --description 'print a help message and exit.'
complete -c lsinitrd -s s -l size --description 'sort the contents of the initramfs by size.'
complete -c lsinitrd -s f -l 'file<filename>' --description 'print the contents of <filename>.'
complete -c lsinitrd -s k -l 'kver<kernel' --description 'inspect the initramfs of <kernel version>.'
complete -c lsinitrd -l file --description '.'
complete -c lsinitrd -l kver --description '.'

