# lvmpolld
# Autogenerated from man page /usr/share/man/man8/lvmpolld.8.gz
# using Deroffing man parser
complete -c lvmpolld -s f -l foreground --description 'Don\'t fork, but run in the foreground.'
complete -c lvmpolld -s h -l help --description 'Show help information.'
complete -c lvmpolld -s l -l log --description 'Select the type of log messages to generate.'
complete -c lvmpolld -s p -l pidfile --description 'Path to the pidfile.'
complete -c lvmpolld -s s -l socket --description 'Path to the socket file.'
complete -c lvmpolld -s t -l timeout --description 'The daemon may shutdown after being idle for th… [See Man Page]'
complete -c lvmpolld -s B -l binary --description 'Optional path to alternative LVM binary (default: /sbin/lvm).'
complete -c lvmpolld -s V -l version --description 'Display the version of lvmpolld daemon.'
complete -c lvmpolld -l dump --description 'Contact the running lvmpolld daemon to obtain t… [See Man Page]'

