# lxt2miner
# Autogenerated from man page /usr/share/man/man1/lxt2miner.1.gz
# using Type1
complete -c lxt2miner -s d -l dumpfile --description 'Specify LXT2 input dumpfile.'
complete -c lxt2miner -s m -l match --description 'Specifies "bitwise" match data (binary, real, string).'
complete -c lxt2miner -s x -l hex --description 'Specifies hexadecimal match data that will auto… [See Man Page]'
complete -c lxt2miner -s n -l namesonly --description 'Indicates that only facnames should be printed … [See Man Page]'
complete -c lxt2miner -s c -l comprehensive --description 'Indicates that results are not to stop after the first match.'

