# lxt2vcd
# Autogenerated from man page /usr/share/man/man1/lxt2vcd.1.gz
# using Deroffing man parser
complete -c lxt2vcd -s l -l lxtname --description 'Specify LXT2 input filename.'
complete -c lxt2vcd -s o -l output --description 'Specify optional VCD output filename.'
complete -c lxt2vcd -s f -l flatearth --description 'Emit flattened hierarchies.'
complete -c lxt2vcd -s n -l notruncate --description 'Do not shorten bitvectors.'
complete -c lxt2vcd -s h -l help --description 'Display help then exit.'

