# mathspic
# Autogenerated from man page /usr/share/man/man1/mathspic.1.gz
# using Deroffing man parser
complete -c mathspic -s b --description 'enables beep if mathsPIC detects an error.'
complete -c mathspic -s c --description 'disables the writing of comments to output file.'
complete -c mathspic -s h --description 'displays the help file.'
complete -c mathspic -s o --description 'defines the output file name MACRO COMMANDS mac… [See Man Page]'

