# mftraining
# Autogenerated from man page /usr/share/man/man1/mftraining.1.gz
# using Deroffing man parser
complete -c mftraining -s U --description '(Input) The unicharset generated by unicharset_extractor(1).'
complete -c mftraining -s F --description '(Input) font properties file, each line is of t… [See Man Page]'
complete -c mftraining -s X --description '(Input) x heights file, each line is of the fol… [See Man Page]'
complete -c mftraining -s D --description 'Directory to write output files to.'
complete -c mftraining -s O --description '(Output) The output unicharset that will be giv… [See Man Page]'

