# ministat
# Autogenerated from man page /usr/share/man/man1/ministat.1.gz
# using Darwin man parser
complete -c ministat -s A --description 'Just report the statistics of the input and rel… [See Man Page]'
complete -c ministat -s n --description 'Just report the raw statistics of the input, su… [See Man Page]'
complete -c ministat -s s --description 'Print the average/median/stddev bars on separat… [See Man Page]'
complete -c ministat -s C --description 'Specify which column of data to use.'
complete -c ministat -s c --description 'Specify desired confidence level for Student\'s T analysis.'
complete -c ministat -s d --description 'Specifies the column delimiter characters, defa… [See Man Page]'
complete -c ministat -s w --description 'Width of ASCII-art plot in characters.'

