# mkinitrd
# Autogenerated from man page /usr/share/man/man8/mkinitrd.8.gz
# using Deroffing man parser
complete -c mkinitrd -l version --description 'print info about the version.'
complete -c mkinitrd -s v -l verbose --description 'increase verbosity level.'
complete -c mkinitrd -s f -l force --description 'overwrite existing initramfs file.'
complete -c mkinitrd -l with --description 'add the kernel module <module> to the initramfs.'
complete -c mkinitrd -l preload --description 'preload the kernel module <module> in the initr… [See Man Page]'
complete -c mkinitrd -l nocompress --description 'do not compress the resulting image.'
complete -c mkinitrd -l help --description 'print a help message and exit.'

