# mkusb
# Autogenerated from man page /usr/share/man/man8/mkusb.8.gz
# using Deroffing man parser
complete -c mkusb -s d --description 'Select dialog menus if available.'
complete -c mkusb -s h --description 'Print a summary of command line options and exit.'
complete -c mkusb -s t --description 'Select a plain text interface.'
complete -c mkusb -s v --description 'Print the current version and exit.'
complete -c mkusb -s z --description 'Select zenity menus if available (default).'

