# mkusb-nox
# Autogenerated from man page /usr/share/man/man8/mkusb-nox.8.gz
# using Deroffing man parser
complete -c mkusb-nox -s h --description 'Print a summary of command line options and exit.'
complete -c mkusb-nox -s v --description 'Print the current version and exit.'

