# mongoperf
# Autogenerated from man page /usr/share/man/man1/mongoperf.1.gz
# using Deroffing man parser
complete -c mongoperf -l help -s h --description 'Returns information on the options and use of mongoperf.'

