# mpeg2desc
# Autogenerated from man page /usr/share/man/man1/mpeg2desc.1.gz
# using Type1
complete -c mpeg2desc -s a --description 'Output audio stream to stdout.'
complete -c mpeg2desc -s v --description 'Output video stream to stdout.'
complete -c mpeg2desc -s o --description 'output the previous stream to FILE instead of stdout.'
complete -c mpeg2desc -s s --description 'skip to first valid header -- ensures mplex can handle output.'
complete -c mpeg2desc -s m --description 'output mplex offset to stdout.'

