# mptopdf
# Autogenerated from man page /usr/share/man/man1/mptopdf.1.gz
# using Deroffing man parser
complete -c mptopdf -l metafun --description 'use the metafun format to process the file (default is mpost).'
complete -c mptopdf -l texexec --description 'use texexec (context) to process text snippets.'
complete -c mptopdf -l latex --description 'use latex to process text snippets AUTHOR More … [See Man Page]'

