# mshrable
# Autogenerated from man page /usr/share/man/man1/mshrable.1.gz
# using Type1
complete -c mshrable -s o --description 'Filename of generated Dolfin mesh.'
complete -c mshrable -s r --description 'Resolution of result mesh.'
complete -c mshrable -s s --description 'Write some statistics of the mesh to stdout.'
complete -c mshrable -l polyout --description 'Write the polyhedron to .'
complete -c mshrable -l polystats --description 'Write statistics of polyhedron (and do not create a  mesh).'
complete -c mshrable -s b --description 'Use 3D mesh generation backend [tetgen|cgal].'
complete -c mshrable -l degenerate_tolerance --description 'Tolerance for considering a facet as degenerate.'
complete -c mshrable -l check-mesh --description 'Check consistency of output mesh (most for debugging/testing.'
complete -c mshrable -s v --description 'Output more information about what is going on.'

