# mtx-unzip
# Autogenerated from man page /usr/share/man/man1/mtx-unzip.1.gz
# using Deroffing man parser
complete -c mtx-unzip -l list --description 'list files in archive.'
complete -c mtx-unzip -l junk --description 'flatten unzipped directory structure.'
complete -c mtx-unzip -l extract --description 'extract files AUTHOR More information about Con… [See Man Page]'

