# mtx-cache
# Autogenerated from man page /usr/share/man/man1/mtx-cache.1.gz
# using Deroffing man parser
complete -c mtx-cache -l purge --description 'remove not used files.'
complete -c mtx-cache -l erase --description 'completely remove cache.'
complete -c mtx-cache -l list --description 'show cache.'
complete -c mtx-cache -l all --description 'all (not yet implemented) AUTHOR More informati… [See Man Page]'

