# mtx-unicode
# Autogenerated from man page /Library/TeX/texbin/man/man1/mtx-unicode.1
complete -c mtx-unicode -l whatever --description 'do whatever AUTHOR More information about ConTeXt and the tools that come wit…'

