# mtx-metatex
# Autogenerated from man page /usr/share/man/man1/mtx-metatex.1.gz
# using Deroffing man parser
complete -c mtx-metatex -l run --description 'process (one or more) files (default action).'
complete -c mtx-metatex -l make --description 'create metatex format(s) AUTHOR More informatio… [See Man Page]'

