# mtx-bibtex
# Autogenerated from man page /Library/TeX/texbin/man/man1/mtx-bibtex.1
complete -c mtx-bibtex -l toxml --description 'convert bibtex database(s) to xml.'
complete -c mtx-bibtex -l tolua --description 'convert bibtex database(s) to lua.'
complete -c mtx-bibtex -l search --description 'seatch bibtex database(s) AUTHOR More information about ConTeXt and the tools…'

