# mtx-dvi
# Autogenerated from man page /Library/TeX/texbin/man/man1/mtx-dvi.1
complete -c mtx-dvi -l list --description 'list dvi commands AUTHOR More information about ConTeXt and the tools that co…'

