# mtx-texworks
# Autogenerated from man page /usr/share/man/man1/mtx-texworks.1.gz
# using Deroffing man parser
complete -c mtx-texworks -l start --description '[--verbose]   start texworks.'
complete -c mtx-texworks -l test --description 'report what will happen AUTHOR More information… [See Man Page]'

