# mtx-evohome
# Autogenerated from man page /Library/TeX/texbin/man/man1/mtx-evohome.1
complete -c mtx-evohome -l collect --description 'collect data from device.'
complete -c mtx-evohome -l presets --description 'file with authenciation data.'
complete -c mtx-evohome -l auto --description 'fetch temperature data every hour.'
complete -c mtx-evohome -l port --description 'server port when running the service, default: 8068.'
complete -c mtx-evohome -l host --description 'server host when running the service, default: localhost AUTHOR More informat…'

