# mtx-rsync
# Autogenerated from man page /usr/share/man/man1/mtx-rsync.1.gz
# using Deroffing man parser
complete -c mtx-rsync -l job --description 'use given file as specification.'
complete -c mtx-rsync -l dryrun --description 'show what would happen.'
complete -c mtx-rsync -l force --description 'force run AUTHOR More information about ConTeXt… [See Man Page]'

