# mtx-check
# Autogenerated from man page /usr/share/man/man1/mtx-check.1.gz
# using Deroffing man parser
complete -c mtx-check -l check --description 'check tex file for errors AUTHOR More informati… [See Man Page]'

