# mtx-colors
# Autogenerated from man page /usr/share/man/man1/mtx-colors.1.gz
# using Deroffing man parser
complete -c mtx-colors -l table --description 'show icc table AUTHOR More information about Co… [See Man Page]'

