# mtx-grep
# Autogenerated from man page /usr/share/man/man1/mtx-grep.1.gz
# using Deroffing man parser
complete -c mtx-grep -l pattern --description 'search for pattern (optional).'
complete -c mtx-grep -l count --description 'count matches only.'
complete -c mtx-grep -l nocomment --description 'skip lines that start with %% or #.'
complete -c mtx-grep -l xml --description 'pattern is lpath expression AUTHOR More informa… [See Man Page]'

