# musixtex
# Autogenerated from man page /usr/share/man/man1/musixtex.1.gz
# using Deroffing man parser
complete -c musixtex -s v --description 'output program name and version number, and quit.'
complete -c musixtex -s h --description 'output usage summary and quit.'
complete -c musixtex -s l --description 'assumes LaTeX source; implied if the file has . ltx extension.'
complete -c musixtex -s p --description 'changes the TeX processor to   pdfetex (1)  or … [See Man Page]'
complete -c musixtex -s c --description 'preprocess pmx file using   pmxchords (1).'
complete -c musixtex -s d --description 'changes the dvi processor to  dvipdfm (1).'
complete -c musixtex -s F --description 'uses   fmt as the TeX processor.'
complete -c musixtex -s m --description 'stops processing at the pmx file.'
complete -c musixtex -s t --description 'stops processing at the tex/mid files.'
complete -c musixtex -s s --description 'stops processing at the dvi file.'
complete -c musixtex -s g --description 'stops processing at the ps file.'
complete -c musixtex -s i --description 'retain intermediate and log files.'
complete -c musixtex -s 1 --description 'one-pass [pdf][la]tex processing; i. e.'
complete -c musixtex -s x --description 'call   makeindex (1) to update index database.'
complete -c musixtex -s f --description 'restore default processing.'
complete -c musixtex -s q --description 'quiet mode (only musixtex\'s own messages); othe… [See Man Page]'
complete -c musixtex -o 'lx.' --description 'Note that four TeX engines are available via th… [See Man Page]'

