# nedit-nc
# Autogenerated from man page /usr/share/man/man1/nedit-nc.1.gz
# using Type1
complete -c nedit-nc -o read --description 'Open the file read-only regardless of the actua… [See Man Page]'
complete -c nedit-nc -o create --description 'Don\'t warn about file creation when a file doesn\'t exist.'
complete -c nedit-nc -o line --description 'Go to line number n.'
complete -c nedit-nc -o do --description 'Execute an NEdit macro or action on the file fo… [See Man Page]'
complete -c nedit-nc -o ask -o noask --description 'Instructs nedit-nc whether to automatically sta… [See Man Page]'
complete -c nedit-nc -o svrname --description 'Explicitly instructs nedit-nc which server to c… [See Man Page]'
complete -c nedit-nc -o svrcmd --description 'The command which nedit-nc uses to start an NEdit server.'
complete -c nedit-nc -o lm --description 'Initial language mode used for editing succeeding files.'
complete -c nedit-nc -o geometry -s g --description 'The initial size and/or location of editor windows.'
complete -c nedit-nc -o icon -o iconic --description 'Initial window state for succeeding files.'
complete -c nedit-nc -o display --description 'The name of the X server to use.'
complete -c nedit-nc -o timeout --description 'Basic time-out period (in seconds) used in comm… [See Man Page]'
complete -c nedit-nc -o wait --description 'Instructs nedit-nc not to return to the shell u… [See Man Page]'
complete -c nedit-nc -o xrm --description 'Set the value of an X resource to override a default value.'
complete -c nedit-nc -o tabbed --description 'Open all subsequent files in new tabs.  Resets -group option.'
complete -c nedit-nc -o untabbed --description 'Open all subsequent files in new windows.'
complete -c nedit-nc -o group --description 'Open all subsequent files as tabs in a new window.'
complete -c nedit-nc -s V -o version --description 'Prints version and build information, to be men… [See Man Page]'
complete -c nedit-nc -s h -o help --description 'Prints the command line help and then exits.'

