# nfsstat
# Autogenerated from man page /usr/share/man/man8/nfsstat.8.gz
# using Deroffing man parser
complete -c nfsstat -s s -l server --description 'Print only server-side statistics.'
complete -c nfsstat -s c -l client --description 'Print only client-side statistics.'
complete -c nfsstat -s n -l nfs --description 'Print only NFS statistics.'
complete -c nfsstat -s 2 --description 'Print only NFS v2 statistics.'
complete -c nfsstat -s 3 --description 'Print only NFS v3 statistics.'
complete -c nfsstat -s 4 --description 'Print only NFS v4 statistics.'
complete -c nfsstat -s m -l mounts --description 'Print information about each of the mounted NFS file systems.'
complete -c nfsstat -s r -l rpc --description 'Print only RPC statistics.'
complete -c nfsstat -s o --description 'Display statistics for the specified facility, … [See Man Page]'
complete -c nfsstat -s v -l verbose --description 'This is equivalent to -o all.'
complete -c nfsstat -s l -l list --description 'Print information in list form.'
complete -c nfsstat -s S -l since --description 'Instead of printing current statistics,   nfsst… [See Man Page]'
complete -c nfsstat -o 'Z[interval]' -l sleep --description 'Instead of printing current statistics and imme… [See Man Page]'

