# nodeusers
# Autogenerated from man page /usr/share/man/man1/nodeusers.1.gz
# using Deroffing man parser
complete -c nodeusers -s a --description 'Tells nodeusers to use a plain <CR> as end-of-line.'
complete -c nodeusers -s i --description 'Tells nodeusers to use a <CR><LF> pair as end-o… [See Man Page]'
complete -c nodeusers -s l --description 'Enables logging of errors to the system logging facility.'

