# npm-dist-tag
# Autogenerated from man page /usr/local/share/man/man1/npm-dist-tag.1
complete -c npm-dist-tag -l tag --description 'auth-and-writes then youâll need to include a one-time password on the comm…'

