# npm-init
# Autogenerated from man page /usr/local/share/man/man1/npm-init.1
complete -c npm-init -l hello -l hello --description '.'
complete -c npm-init -o y/--yes -l scope --description 'will create a scoped package.  SEE ALSO.'

