# nslookup
# Autogenerated from man page /usr/share/man/man1/nslookup.1.gz
# using Deroffing man parser
complete -c nslookup -o version --description 'option causes nslookup to print the version num… [See Man Page]'

