# ocamloptp
# Autogenerated from man page /usr/share/man/man1/ocamloptp.1.gz
# using Deroffing man parser
complete -c ocamloptp -o pp --description 'option is not supported.'
complete -c ocamloptp -s P --description 'option.'
complete -c ocamloptp -s p --description 'with the same argument and meaning as.'

