# okular
# Autogenerated from man page /usr/share/man/man1/okular.1.gz
# using Deroffing man parser
complete -c okular -l help --description '.'
complete -c okular -l help-qt --description '.'
complete -c okular -l help-kde --description '.'
complete -c okular -l help-all --description '.'
complete -c okular -l author --description '.'
complete -c okular -s v -l version --description '.'
complete -c okular -l license --description '.'
complete -c okular -s p -l page --description '.'
complete -c okular -l presentation --description '.'
complete -c okular -l print --description '.'
complete -c okular -l unique --description '.'
complete -c okular -l noraise --description '.'

