# opalcc
# Autogenerated from man page /usr/share/man/man1/opalcc.1.gz
# using Deroffing man parser
complete -c opalcc -l showme --description 'This option comes in several different variants (see below).'
complete -c opalcc -l showme:compile --description 'Output the compiler flags that would have been … [See Man Page]'
complete -c opalcc -l showme:link --description 'Output the linker flags that would have been su… [See Man Page]'
complete -c opalcc -l showme:command --description 'Outputs the underlying C compiler command (whic… [See Man Page]'
complete -c opalcc -l showme:incdirs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c opalcc -l showme:libdirs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c opalcc -l showme:libs --description 'Outputs a space-delimited (but otherwise undeco… [See Man Page]'
complete -c opalcc -l showme:version --description 'Outputs the version number of Open MPI.'
complete -c opalcc -l showme:help --description 'Output a brief usage help message.'
complete -c opalcc -o qfixed --description 'may be necessary to compile fixed-format Fortran source files.'
complete -c opalcc -o m64 --description 'build, but can be activated (for example, in a … [See Man Page]'

