# opencv_createsamples
# Autogenerated from man page /usr/share/man/man1/opencv_createsamples.1.gz
# using Deroffing man parser
complete -c opencv_createsamples -o info --description 'A database of positive source images.'
complete -c opencv_createsamples -o img --description 'A positive source image.'
complete -c opencv_createsamples -o vec --description 'The output file name containing the generated p… [See Man Page]'
complete -c opencv_createsamples -o bg --description 'The background description file (the negative sample set).'
complete -c opencv_createsamples -o num --description 'The number of positive samples to generate/train.'
complete -c opencv_createsamples -o bgcolor --description 'The background color (currently grayscale image… [See Man Page]'
complete -c opencv_createsamples -o inv --description 'Invert the colors.'
complete -c opencv_createsamples -o maxidev --description 'The desired maximum intensity deviation of fore… [See Man Page]'
complete -c opencv_createsamples -o maxxangle --description 'The maximum rotation angle in x-direction in radians.'
complete -c opencv_createsamples -o maxyangle --description 'The maximum rotation angle in y-direction in radians.'
complete -c opencv_createsamples -o maxzangle --description 'The maximum rotation angle in z-direction in radians.'
complete -c opencv_createsamples -o show --description 'Show each created sample during the creation process.'
complete -c opencv_createsamples -s h --description 'For the creation of training samples, it is the… [See Man Page]'
complete -c opencv_createsamples -s w --description 'For the creation of training samples, it is the… [See Man Page]'

