# openocd
# Autogenerated from man page /usr/share/man/man1/openocd.1.gz
# using Type1
complete -c openocd -s f -l file --description 'This is a shortcut for a -c "[script <filename>… [See Man Page]'
complete -c openocd -s s -l search --description 'Add  <dirname> to the search path used for conf… [See Man Page]'
complete -c openocd -s d -l debug --description 'Set debug level.  Possible values are: . br .'
complete -c openocd -s l -l log_output --description 'Redirect log output to the file R <filename> .'
complete -c openocd -s c -l command --description 'Add the command  <cmd> to a list of commands ex… [See Man Page]'
complete -c openocd -s p -l pipe --description 'Use pipes when talking to gdb.'
complete -c openocd -s h -l help --description 'Show a help text and exit.'

