# opt-4
# Autogenerated from man page /usr/share/man/man1/opt-4.0.1.gz
# using Deroffing man parser
complete -c opt-4 -s f --description 'Enable binary output on terminals.'
complete -c opt-4 -o help --description 'Print a summary of command line options. UNINDENT NDENT 0. 0.'
complete -c opt-4 -s o --description 'Specify the output filename. UNINDENT NDENT 0. 0.'
complete -c opt-4 -s S --description 'Write output in LLVM intermediate language (ins… [See Man Page]'
complete -c opt-4 -o '{passname}' --description 'opt provides the ability to run any of LLVM\\(aq… [See Man Page]'
complete -c opt-4 -o disable-inlining --description 'This option simply removes the inlining pass fr… [See Man Page]'
complete -c opt-4 -o disable-opt --description 'This option is only meaningful when -std-link-opts is given.'
complete -c opt-4 -o strip-debug --description 'This option causes opt to strip debug informati… [See Man Page]'
complete -c opt-4 -o verify-each --description 'This option causes opt to add a verify pass aft… [See Man Page]'
complete -c opt-4 -o stats --description 'Print statistics. UNINDENT NDENT 0. 0.'
complete -c opt-4 -o time-passes --description 'Record the amount of time needed for each pass … [See Man Page]'
complete -c opt-4 -o debug --description 'If this is a debug build, this option will enab… [See Man Page]'
complete -c opt-4 -o load --description 'Load the dynamic object plugin.'
complete -c opt-4 -s p --description 'Print module after each transformation.'

