# pdfjadetex
# Autogenerated from man page /usr/share/man/man1/pdfjadetex.1.gz
# using Deroffing man parser
complete -c pdfjadetex -l fmt --description 'Use  format as the name of the format to be use… [See Man Page]'
complete -c pdfjadetex -l help --description 'Print help message and exit.'
complete -c pdfjadetex -l ini --description 'Be  pdfinitex , for dumping formats; this is im… [See Man Page]'
complete -c pdfjadetex -l interaction --description 'Sets the interaction mode.'
complete -c pdfjadetex -l ipc --description 'Send DVI or PDF output to a socket as well as t… [See Man Page]'
complete -c pdfjadetex -l ipc-start --description 'As  --ipc , and starts the server at the other end as well.'
complete -c pdfjadetex -l kpathsea-debug --description 'Sets path searching debugging flags according to the bitmask.'
complete -c pdfjadetex -l maketex --description 'Enable .'
complete -c pdfjadetex -l no-maketex --description 'Disable .'
complete -c pdfjadetex -l output-comment --description 'Use  string for the DVI file comment instead of the date.'
complete -c pdfjadetex -l progname --description 'Pretend to be program R name .'
complete -c pdfjadetex -l shell-escape --description 'Enable the  write18command construct.'
complete -c pdfjadetex -l version --description '.'

