# perf-diff
# Autogenerated from man page /usr/share/man/man1/perf-diff.1.gz
# using Deroffing man parser
complete -c perf-diff -s D -l dump-raw-trace --description 'Dump raw trace in ASCII.'
complete -c perf-diff -l kallsyms --description 'kallsyms pathname.'
complete -c perf-diff -s m -l modules --description 'Load module symbols.'
complete -c perf-diff -s d -l dsos --description 'Only consider symbols in these dsos.'
complete -c perf-diff -s C -l comms --description 'Only consider symbols in these comms.'
complete -c perf-diff -s S -l symbols --description 'Only consider these symbols.'
complete -c perf-diff -s s -l sort --description 'Sort by key(s): pid, comm, dso, symbol, cpu, parent, srcline.'
complete -c perf-diff -s t -l field-separator --description 'Use a special separator character and don\\(cqt … [See Man Page]'
complete -c perf-diff -s v -l verbose --description 'Be verbose, for instance, show the raw counts i… [See Man Page]'
complete -c perf-diff -s f -l force --description 'Don\\(cqt complain, do it.'
complete -c perf-diff -l symfs --description 'Look for files with symbols relative to this directory.'
complete -c perf-diff -s b -l baseline-only --description 'Show only items with match in baseline.'
complete -c perf-diff -s c -l compute --description 'Differential computation selection - delta,rati… [See Man Page]'
complete -c perf-diff -s p -l period --description 'Show period values for both compared hist entries.'
complete -c perf-diff -s F -l formula --description 'Show formula for given computation.'
complete -c perf-diff -s o -l order --description 'Specify compute sorting column number.'
complete -c perf-diff -l percentage --description 'Determine how to display the overhead percentag… [See Man Page]'
complete -c perf-diff -l ------------------------------------- --description 'b                    x          f1 b          x… [See Man Page]'

