# perf-sched
# Autogenerated from man page /usr/share/man/man1/perf-sched.1.gz
# using Deroffing man parser
complete -c perf-sched -s i -l input --description 'Input file name.  (default: perf. data unless stdin is a fifo).'
complete -c perf-sched -s v -l verbose --description 'Be more verbose.  (show symbol address, etc).'
complete -c perf-sched -s D -l dump-raw-trace --description 'Display verbose dump of the sched data.'

