# perf-kmem
# Autogenerated from man page /usr/share/man/man1/perf-kmem.1.gz
# using Deroffing man parser
complete -c perf-kmem -s i -l input --description 'Select the input file (default: perf.'
complete -c perf-kmem -s v -l verbose --description 'Be more verbose.  (show symbol address, etc).'
complete -c perf-kmem -l caller --description 'Show per-callsite statistics.'
complete -c perf-kmem -l alloc --description 'Show per-allocation statistics.'
complete -c perf-kmem -s s -l sort --description 'Sort the output (default: frag,hit,bytes for sl… [See Man Page]'
complete -c perf-kmem -s l -l line --description 'Print n lines only.'
complete -c perf-kmem -l raw-ip --description 'Print raw ip instead of symbol.'
complete -c perf-kmem -l slab --description 'Analyze SLAB allocator events.'
complete -c perf-kmem -l page --description 'Analyze page allocator events.'
complete -c perf-kmem -l live --description 'Show live page stat.'

