# perf-mem
# Autogenerated from man page /usr/share/man/man1/perf-mem.1.gz
# using Deroffing man parser
complete -c perf-mem -s t -l type --description 'Select the memory operation type: load or store… [See Man Page]'
complete -c perf-mem -s D -l dump-raw-samples --description 'Dump the raw decoded samples on the screen in a… [See Man Page]'
complete -c perf-mem -s x -l field-separator --description 'Specify the field separator used when dump raw … [See Man Page]'
complete -c perf-mem -s C -l cpu-list --description 'Restrict dump of raw samples to those provided via this option.'

