# perf-probe
# Autogenerated from man page /usr/share/man/man1/perf-probe.1.gz
# using Deroffing man parser
complete -c perf-probe -s k -l vmlinux --description 'Specify vmlinux path which has debuginfo (Dwarf binary).'
complete -c perf-probe -s m -l module --description 'Specify module name in which perf-probe searche… [See Man Page]'
complete -c perf-probe -s s -l source --description 'Specify path to kernel source.'
complete -c perf-probe -s v -l verbose --description 'Be more verbose (show parsed arguments, etc).'
complete -c perf-probe -s q -l quiet --description 'Be quiet (do not show any messages including errors).'
complete -c perf-probe -s a -l add --description 'Define a probe event (see PROBE SYNTAX for detail).'
complete -c perf-probe -s d -l del --description 'Delete probe events.'
complete -c perf-probe -s l -l 'list[' --description 'List up current probe events.'
complete -c perf-probe -s L -l line --description 'Show source code lines which can be probed.'
complete -c perf-probe -s V -l vars --description 'Show available local variables at given probe point.'
complete -c perf-probe -l externs --description '(Only for --vars) Show external defined variabl… [See Man Page]'
complete -c perf-probe -l no-inlines --description '(Only for --add) Search only for non-inlined functions.'
complete -c perf-probe -s F -l 'funcs[' --description 'Show available functions in given module or kernel.'
complete -c perf-probe -l filter --description '(Only for --vars and --funcs) Set filter.'
complete -c perf-probe -s f -l force --description 'Forcibly add events with existing name.'
complete -c perf-probe -s n -l dry-run --description 'Dry run.'
complete -c perf-probe -l max-probes --description 'Set the maximum number of probe points for an event.'
complete -c perf-probe -s x -l exec --description 'Specify path to the executable or shared librar… [See Man Page]'
complete -c perf-probe -l demangle --description 'Demangle application symbols.'
complete -c perf-probe -l demangle-kernel --description 'Demangle kernel symbols.'

