# perf-script-python
# Autogenerated from man page /usr/share/man/man1/perf-script-python.1.gz
# using Deroffing man parser
complete -c perf-script-python -l -------------------------------------- -l --------- --description 'sys_write                                     4… [See Man Page]'
complete -c perf-script-python -o rw-r--r-- --description 'drwxr-xr-x 3 trz trz 4096 2010-01-26 22:49 Perf-Trace-Util.'

