# perf-test
# Autogenerated from man page /usr/share/man/man1/perf-test.1.gz
# using Deroffing man parser
complete -c perf-test -s s -l skip --description 'Tests to skip (comma separated numeric list).'
complete -c perf-test -s v -l verbose --description 'Be more verbose.'

