# pinentry
# Autogenerated from man page /usr/share/man/man1/pinentry.1.gz
# using Deroffing man parser
complete -c pinentry -l version --description 'Print the program version and licensing information.'
complete -c pinentry -l help --description 'Print a usage message summarizing the most usef… [See Man Page]'
complete -c pinentry -l debug -s d --description 'Turn on some debugging.   Mostly useful for the maintainers.'
complete -c pinentry -l enhanced -s e --description 'Ask for timeouts and insurance, too.'
complete -c pinentry -l no-global-grab -s g --description 'Grab the keyboard only when the window is focused.'
complete -c pinentry -l parent-wid --description 'Use window ID N as the parent window for positi… [See Man Page]'
complete -c pinentry -l display -l ttyname -l ttytype -l lc-type -l lc-messages --description 'These options are used to pass localization inf… [See Man Page]'

