# plainbox-qml-shell
# Autogenerated from man page /usr/share/man/man1/plainbox-qml-shell.1.gz
# using Deroffing man parser
complete -c plainbox-qml-shell -l version --description 'show program\\(aqs version number and exit.'
complete -c plainbox-qml-shell -s v -l verbose --description 'be more verbose (same as --log-level=INFO).'
complete -c plainbox-qml-shell -s D -l debug --description 'enable DEBUG messages on the root logger.'
complete -c plainbox-qml-shell -s C -l debug-console --description 'display DEBUG messages in the console.'
complete -c plainbox-qml-shell -s T -l trace --description 'enable DEBUG messages on the specified logger (… [See Man Page]'
complete -c plainbox-qml-shell -s P -l pdb --description 'jump into pdb (python debugger) when a command crashes.'
complete -c plainbox-qml-shell -s I -l debug-interrupt --description 'crash on SIGINT/KeyboardInterrupt, useful with --pdb.'

