# plainbox-trusted-launcher-1
# Autogenerated from man page /usr/share/man/man1/plainbox-trusted-launcher-1.1.gz
# using Deroffing man parser
complete -c plainbox-trusted-launcher-1 -s w -l warmup --description 'return immediately, only useful when used with pkexec(1).'
complete -c plainbox-trusted-launcher-1 -s t -l target --description 'run a job with this checksum.'
complete -c plainbox-trusted-launcher-1 -s T -l target-environment --description 'environment passed to the target job.'
complete -c plainbox-trusted-launcher-1 -s g -l generator --description 'also run a job with this checksum (assuming it is a local job).'
complete -c plainbox-trusted-launcher-1 -l generator-environment --description '.'
complete -c plainbox-trusted-launcher-1 -s G --description 'environment passed to the generator job.'

