# policyeditor
# Autogenerated from man page /usr/share/man/man1/policyeditor.1.gz
# using Deroffing man parser
complete -c policyeditor -o codebase --description 'Specifies an applet codebase URL.'
complete -c policyeditor -o defaultfile --description 'Specifies that the default user-level policy fi… [See Man Page]'
complete -c policyeditor -o file --description 'Specifies a policy file path to open.'
complete -c policyeditor -o help --description 'Prints out information about supported command and basic usage.'
complete -c policyeditor -o verbose --description 'Enable verbose output. (No argument expected).'

