# powershell
# Autogenerated from man page /usr/local/share/man/man1/powershell.1.gz
complete -c powershell -o NoLogo --description 'Hides the copyright banner at startup.'
complete -c powershell -o NoExit --description 'Does not exit after running startup commands.'
complete -c powershell -o NoProfile --description 'Does not load the PowerShell profile.'
complete -c powershell -o NonInteractive --description 'Does not present an interactive prompt to the user.'
complete -c powershell -o InputFormat --description 'Describes the format of data sent to PowerShell.'
complete -c powershell -o OutputFormat --description 'Determines how output from PowerShell is formatted.'
complete -c powershell -o EncodedCommand --description 'Accepts a base-64-encoded string version of a command.'
complete -c powershell -o File --description 'Runs the specified script in the local scope ("dot-sourced"), so that the fun…'
complete -c powershell -o ExecutionPolicy --description 'Sets the default execution policy for the current session and saves it in the…'
complete -c powershell -o Command --description 'Executes the specified commands (and any parameters) as though they were type…'

