# pp-trace-3
# Autogenerated from man page /usr/share/man/man1/pp-trace-3.7.1.gz
# using Deroffing man parser
complete -c pp-trace-3 -o gpsize --description 'The default size is 8.'
complete -c pp-trace-3 -o enable-implicit-null-checks --description '.'
complete -c pp-trace-3 -o imp-null-check-page-size --description '.'
complete -c pp-trace-3 -o help-list --description '.'

