# psppire
# Autogenerated from man page /usr/share/man/man1/psppire.1.gz
# using Deroffing man parser
complete -c psppire -l help --description 'Show summary of options.'
complete -c psppire -l version --description 'Show version of program.  EXAMPLE Create a file example.'

