# pspp
# Autogenerated from man page /usr/share/man/man1/pspp.1.gz
# using Deroffing man parser
complete -c pspp -l help --description 'Show summary of options.'
complete -c pspp -l version --description 'Show version of program.  EXAMPLE Create a file example.'

