# pspp-convert
# Autogenerated from man page /usr/share/man/man1/pspp-convert.1.gz
# using Type1
complete -c pspp-convert -s O --description 'Q "--output-format=format" Specifies the desired output format.'
complete -c pspp-convert -s c --description 'Q "--cases=maxcases" By default, all cases are … [See Man Page]'
complete -c pspp-convert -s e --description 'Q "--encoding=charset" Overrides the encoding i… [See Man Page]'
complete -c pspp-convert -s p --description 'Q "--password=password" Specifies the password … [See Man Page]'
complete -c pspp-convert -s h --description 'Q "--help" Prints a usage message on stdout and exits.'

