# pspp-dump-sav
# Autogenerated from man page /usr/share/man/man1/pspp-dump-sav.1.gz
# using Type1
complete -c pspp-dump-sav -o 'd[maxcases]' --description 'Q "--data[=maxcases]" By default, pspp-dump-sav… [See Man Page]'
complete -c pspp-dump-sav -s h --description 'Q "--help" Prints a usage message on stdout and exits.'

