# pstoedit
# Autogenerated from man page /usr/share/man/man1/pstoedit.1.gz
# using Deroffing man parser
complete -c pstoedit -s f --description 'target output format recognized by pstoedit.'
complete -c pstoedit -o bo --description 'dumpfile outfile.'
complete -c pstoedit -o psarg --description '.'
complete -c pstoedit -o help -o 'v.' --description '.'
complete -c pstoedit -o sclip --description 'option to simulate clipping.'

