# pyste
# Autogenerated from man page /usr/share/man/man1/pyste.1.gz
# using Deroffing man parser
complete -c pyste -l module --description 'The name of the module that will be generated; … [See Man Page]'
complete -c pyste -s I --description 'Add an include path.'
complete -c pyste -s D --description 'Define symbol.'
complete -c pyste -l multiple --description 'Create various cpps, instead of only one (usefu… [See Man Page]'
complete -c pyste -l out --description 'Specify output filename (default: <module>.'
complete -c pyste -l no-using --description 'Do not declare "using namespace boost"; use exp… [See Man Page]'
complete -c pyste -l pyste-ns --description 'Set the namespace where new types will be decla… [See Man Page]'
complete -c pyste -l debug --description 'Writes the xml for each file parsed in the current directory.'
complete -c pyste -l cache-dir --description 'Directory for cache files (speeds up future runs).'
complete -c pyste -l only-create-cache --description 'Recreates all caches (doesn\'t generate code).'
complete -c pyste -l generate-main --description 'Generates the _main. cpp file (in multiple mode).'
complete -c pyste -l file-list --description 'A file with one pyste file per line.'
complete -c pyste -l gccxml-path --description 'Path to gccxml executable (default: gccxml).'
complete -c pyste -l no-default-include --description 'Do not use INCLUDE environment variable for inc… [See Man Page]'
complete -c pyste -s h -l help --description 'Print this help and exit.'
complete -c pyste -s v -l version --description 'Print version information.'

