# pyvenv
# Autogenerated from man page /usr/share/man/man1/pyvenv.1.gz
# using Deroffing man parser
complete -c pyvenv -s h -l help --description 'show this help message and exit.'
complete -c pyvenv -l system-site-packages --description 'Give the virtual environment access to the syst… [See Man Page]'
complete -c pyvenv -l symlinks --description 'Attempt to symlink rather than copy.'
complete -c pyvenv -l clear --description 'Delete the environment directory if it already exists.'
complete -c pyvenv -l upgrade --description 'Upgrade the environment directory to use this v… [See Man Page]'

