# racoonctl
# Autogenerated from man page /usr/share/man/man8/racoonctl.8.gz
# using Darwin man parser
complete -c racoonctl -s d --description 'Debug mode.  Hexdump sent admin port commands.'
complete -c racoonctl -s l --description 'Increase verbosity.  Mainly for show-sa command.'
complete -c racoonctl -s s --description 'Specify unix socket name used to connecting racoon.'

