# reordercap
# Autogenerated from man page /usr/share/man/man1/reordercap.1.gz
# using Type1
complete -c reordercap -s n --description 'When the -n option is used, reordercap will not… [See Man Page]'

