# rhino
# Autogenerated from man page /usr/share/man/man1/rhino.1.gz
# using Deroffing man parser
complete -c rhino -o escript_source --description 'Executes script_source as a JavaScript script.'
complete -c rhino -o fscript_filename_or_url --description 'Reads script_filename_or_url content and execut… [See Man Page]'
complete -c rhino -o opt -o OoptLevel --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino -o versionversionNumber --description 'Specifies the language version to compile with.'
complete -c rhino -s e --description 'Executes script_source as a JavaScript script.'
complete -c rhino -s f --description 'Reads script_filename_or_url content and execut… [See Man Page]'
complete -c rhino -s O --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino -o version --description 'Specifies the language version to compile with.'
complete -c rhino -o strict --description 'Enable strict mode.'

