# rhino-jsc
# Autogenerated from man page /usr/share/man/man1/rhino-jsc.1.gz
# using Deroffing man parser
complete -c rhino-jsc -o extendsjava_class_name --description 'Specifies that a java class extending the Java … [See Man Page]'
complete -c rhino-jsc -o implementsjava_intf_name --description 'Specifies that a java class implementing the Ja… [See Man Page]'
complete -c rhino-jsc -o debug -s g --description 'Specifies that debug information should be generated.'
complete -c rhino-jsc -o nosource --description 'Does not save the source in the class file.'
complete -c rhino-jsc -o ooutputFile --description 'Writes the class file to the given file (which should end in .'
complete -c rhino-jsc -o opt -o OoptLevel --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino-jsc -o packagepackageName --description 'Specifies the package to generate the class into.'
complete -c rhino-jsc -o extends --description 'Specifies that a java class extending the Java … [See Man Page]'
complete -c rhino-jsc -o implements --description 'Specifies that a java class implementing the Ja… [See Man Page]'
complete -c rhino-jsc -s o --description 'Writes the class file to the given file (which should end in .'
complete -c rhino-jsc -s O --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino-jsc -o package --description 'Specifies the package to generate the class into.'
complete -c rhino-jsc -o version --description 'Specifies the language version to compile with.'

