# rhino-debugger
# Autogenerated from man page /usr/share/man/man1/rhino-debugger.1.gz
# using Deroffing man parser
complete -c rhino-debugger -o escript_source --description 'Executes script_source as a JavaScript script.'
complete -c rhino-debugger -o fscript_filename_or_url --description 'Reads script_filename_or_url content and execut… [See Man Page]'
complete -c rhino-debugger -o opt -o OoptLevel --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino-debugger -o versionversionNumber --description 'Specifies the language version to compile with.'
complete -c rhino-debugger -s e --description 'Executes script_source as a JavaScript script.'
complete -c rhino-debugger -s f --description 'Reads script_filename_or_url content and execut… [See Man Page]'
complete -c rhino-debugger -s O --description 'Optimizes at level optLevel, which must be an i… [See Man Page]'
complete -c rhino-debugger -o version --description 'Specifies the language version to compile with.'
complete -c rhino-debugger -o strict --description 'Enable strict mode.'

