# rpc
# Autogenerated from man page /usr/share/man/man8/rpc.svcgssd.8.gz
# using Deroffing man parser
complete -c rpc -s i --description 'If the nfsidmap library supports setting debug … [See Man Page]'

