# rpcdebug
# Autogenerated from man page /usr/share/man/man8/rpcdebug.8.gz
# using Deroffing man parser
complete -c rpcdebug -s c --description 'Clear the given debug flags.'
complete -c rpcdebug -s h --description 'Print a help message and exit.'
complete -c rpcdebug -s m --description 'Specify which module\'s flags to set or clear.'
complete -c rpcdebug -s s --description 'Set the given debug flags.'
complete -c rpcdebug -s v --description 'Increase the verbosity of rpcdebug\'s output.'

