# rpdump
# Autogenerated from man page /usr/share/man/man1/rpdump.1.gz
# using Deroffing man parser
complete -c rpdump -s f --description 'Force the dump even if the remote folder is in … [See Man Page]'
complete -c rpdump -s l --description 'The file on this system that is to be copied to.'
complete -c rpdump -s r --description 'A remote folder name to be copied from.'

