# rpload
# Autogenerated from man page /usr/share/man/man1/rpload.1.gz
# using Deroffing man parser
complete -c rpload -s f --description 'Force the load even if the remote folder is in … [See Man Page]'
complete -c rpload -s s --description 'If the number of messages in the remote folder … [See Man Page]'
complete -c rpload -s t --description 'The possible Types are pinerc, abook, and sig.'
complete -c rpload -s l --description 'The file on this system that is to be copied.'
complete -c rpload -s r --description 'A remote folder name to be copied to.'

