# rubikrotation
# Autogenerated from man page /Library/TeX/texbin/man/man1/rubikrotation.1
complete -c rubikrotation -s h --description 'displays the help info and exits.'
complete -c rubikrotation -s v --description 'displays the version info and exits.'
complete -c rubikrotation -s i --description 'defines the input filename.'
complete -c rubikrotation -s o --description 'defines the output filename.'

