# saxon-xslt
# Autogenerated from man page /usr/share/man/man1/saxon-xslt.1.gz
# using Deroffing man parser
complete -c saxon-xslt -s a --description 'Use xml-stylesheet PI, not style-doc argument.'
complete -c saxon-xslt -o ds --description 'Use standard tree data structure.'
complete -c saxon-xslt -o dt --description 'Use tinytree data structure (default).'
complete -c saxon-xslt -s o --description 'Send output to named file or directory.'
complete -c saxon-xslt -s m --description 'Use specified Emitter class for xsl:message output.'
complete -c saxon-xslt -s r --description 'Use specified URIResolver class.'
complete -c saxon-xslt -s t --description 'Display version and timing information.'
complete -c saxon-xslt -s T --description 'Set standard TraceListener.'
complete -c saxon-xslt -o TL --description 'Set a specific TraceListener.'
complete -c saxon-xslt -s u --description 'Names are URLs not filenames.'
complete -c saxon-xslt -o w0 --description 'Recover silently from recoverable errors.'
complete -c saxon-xslt -o w1 --description 'Report recoverable errors and continue (default).'
complete -c saxon-xslt -o w2 --description 'Treat recoverable errors as fatal.'
complete -c saxon-xslt -s x --description 'Use specified SAX parser for source file.'
complete -c saxon-xslt -s y --description 'Use specified SAX parser for stylesheet.'
complete -c saxon-xslt -s '?' --description 'Display this message AUTHOR SAXON 6. 5. 5 from Michael Kay.'

