# sdl-config
# Autogenerated from man page /usr/share/man/man1/sdl-config.1.gz
# using Deroffing man parser
complete -c sdl-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c sdl-config -l 'exec-prefix[' --description 'If DIR is not specified, print the exec prefix … [See Man Page]'
complete -c sdl-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c sdl-config -l static-libs --description 'Print the linker flags that are necessary to st… [See Man Page]'
complete -c sdl-config -l 'prefix[' --description 'If DIR is not specified, print the prefix of th… [See Man Page]'
complete -c sdl-config -l 'static-libs.' --description '.'
complete -c sdl-config -l exec-prefix --description 'the options --cflags, --libs and --static-libs.'
complete -c sdl-config -l version --description 'Prints the currently installed version of SDL o… [See Man Page]'

