# shar
# Autogenerated from man page /usr/share/man/man1/shar.1.gz
# using Deroffing man parser
complete -c shar -l whole-size-limit --description '.'
complete -c shar -l input-file-list -s '.' --description 'NOTE: THIS OPTION IS DEPRECATED Controlling the… [See Man Page]'
complete -c shar -l submitter --description '.'
complete -c shar -l archive-name --description '(/) character, then the /part## is omitted.   Thus.'
complete -c shar -s n --description '.'
complete -c shar -l query-user --description 'overwrite pre-existing files.   In all cases, however, if.'
complete -c shar -l cut-mark --description 'unpacking, then existing files will be overwrit… [See Man Page]'
complete -c shar -l no-timestamp -l force-prefix --description 'get you occasional complaints.'

