# shiboken2
# Autogenerated from man page /usr/share/man/man1/shiboken2.1.gz
# using Deroffing man parser
complete -c shiboken2 -l debug-level --description 'Set the debug level.'
complete -c shiboken2 -l documentation-only --description 'Do not generates any code, just the documentation.'
complete -c shiboken2 -l generatorSet --description 'generatorSet to be used.  e. g.  qtdoc.'
complete -c shiboken2 -l help --description 'Display this help and exit.'
complete -c shiboken2 -l include-paths --description 'Include paths used by the C++ parser.'
complete -c shiboken2 -l license-file --description 'File used for copyright headers of generated files.'
complete -c shiboken2 -l no-suppress-warnings --description 'Show all warnings.'
complete -c shiboken2 -l output-directory --description 'The directory where the generated files will be written.'
complete -c shiboken2 -l silent --description 'Avoid printing any message.'
complete -c shiboken2 -l typesystem-paths --description 'Paths used when searching for typesystems.'
complete -c shiboken2 -l version --description 'Output version information and exit . SS "Shiboken options:".'
complete -c shiboken2 -l disable-verbose-error-messages --description 'Disable verbose error messages.'
complete -c shiboken2 -l enable-parent-ctor-heuristic --description 'Enable heuristics to detect parent relationship… [See Man Page]'
complete -c shiboken2 -l enable-pyside-extensions --description 'Enable PySide extensions, such as support for s… [See Man Page]'
complete -c shiboken2 -l enable-return-value-heuristic --description 'Enable heuristics to detect parent relationship… [See Man Page]'

