# sm-notify
# Autogenerated from man page /usr/share/man/man8/sm-notify.8.gz
# using Deroffing man parser
complete -c sm-notify -s d --description 'Keeps  sm-notify attached to its controlling te… [See Man Page]'
complete -c sm-notify -s f --description 'Send notifications even if  sm-notify has alrea… [See Man Page]'
complete -c sm-notify -s m --description 'Specifies the length of time, in minutes, to co… [See Man Page]'
complete -c sm-notify -s n --description 'Prevents  sm-notify from updating the local sys… [See Man Page]'
complete -c sm-notify -s p --description 'Specifies the source port number  sm-notify sho… [See Man Page]'
complete -c sm-notify -s P -l state-directory-path --description 'Specifies the pathname of the parent directory … [See Man Page]'
complete -c sm-notify -s v --description 'Specifies the network address from which to sen… [See Man Page]'

