# smartd
# Autogenerated from man page /usr/share/man/man8/smartd.8.gz
# using Deroffing man parser
complete -c smartd -s A -l attributelog --description 'Writes smartd attribute information (normalized… [See Man Page]'
complete -c smartd -s B -l drivedb --description '[ATA only] Read the drive database from FILE.'
complete -c smartd -s c -l configfile --description 'Read smartd configuration Directives from FILE,… [See Man Page]'
complete -c smartd -s C -l capabilities --description '[Linux only] Use libcap-ng to drop unneeded Lin… [See Man Page]'
complete -c smartd -s d -l debug --description 'Runs smartd in "debug" mode.'
complete -c smartd -s D -l showdirectives --description 'Prints a list (to STDOUT) of all the possible D… [See Man Page]'
complete -c smartd -s h -l help -l usage --description 'Prints usage message to STDOUT and exits.'
complete -c smartd -s i -l interval --description 'Sets the interval between disk checks to N seco… [See Man Page]'
complete -c smartd -s l -l logfacility --description 'Uses syslog facility FACILITY to log the messages from smartd.'
complete -c smartd -s n -l no-fork --description 'Do not fork into background; this is useful whe… [See Man Page]'
complete -c smartd -s p -l pidfile --description 'Writes pidfile NAME containing the smartd Proce… [See Man Page]'
complete -c smartd -s q -l quit --description 'Specifies when, if ever, smartd should exit.'
complete -c smartd -s r -l report --description 'Intended primarily to help  smartmontools devel… [See Man Page]'
complete -c smartd -s s -l savestates --description 'Reads/writes smartd state information from/to f… [See Man Page]'
complete -c smartd -s w -l warnexec --description 'Run the executable PATH instead of the default … [See Man Page]'
complete -c smartd -l service --description '\\"# [Windows only] Enables smartd to run as a Windows service.'
complete -c smartd -s V -l version -l license -l copyright --description 'Prints version, copyright, license, home page a… [See Man Page]'

