# smpeg-config
# Autogenerated from man page /usr/share/man/man1/smpeg-config.1.gz
# using Deroffing man parser
complete -c smpeg-config -l version --description 'Print the currently installed version of SMPEG … [See Man Page]'
complete -c smpeg-config -l libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c smpeg-config -l library-libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c smpeg-config -l plugin-libs --description 'Print the linker flags that are necessary to li… [See Man Page]'
complete -c smpeg-config -l cflags --description 'Print the compiler flags that are necessary to … [See Man Page]'
complete -c smpeg-config -l prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'
complete -c smpeg-config -l exec-prefix --description 'If specified, use PREFIX instead of the install… [See Man Page]'

