# snap
# Autogenerated from man page /usr/share/man/man1/snap.1.gz
# using Deroffing man parser
complete -c snap -l channel --description 'Install from this channel instead of the device\'s default.'
complete -c snap -l devmode --description 'Install the snap with non-enforcing security in… [See Man Page]'
complete -c snap -s i --description 'constrain listing to specific interfaces known … [See Man Page]'

