# spell
# Autogenerated from man page /usr/share/man/man1/spell.1.gz
# using Deroffing man parser
complete -c spell -s I -l ispell-version --description 'Print Ispell\'s version.'
complete -c spell -s V -l version --description 'Print the version number.'
complete -c spell -s b -l british --description 'Use the British dictionary.'
complete -c spell -s d -l dictionary --description 'Use FILE to look up words.'
complete -c spell -s h -l help --description 'Print a summary of the options.'
complete -c spell -s i -l ispell --description 'Calls PROGRAM as Ispell.'
complete -c spell -s D -l ispell-dictionary --description 'Use the named DICTIONARY to look up words.'
complete -c spell -s l -l all-chains --description 'Ignored; for compatibility.'
complete -c spell -s n -l number --description 'Print line numbers before lines.'
complete -c spell -s o -l print-file-name --description 'Print file names before lines.'
complete -c spell -s s -l stop-list --description 'Ignored; for compatibility.'
complete -c spell -s v -l verbose --description 'Print words not literally found.'
complete -c spell -s x -l print-stems --description 'Ignored; for compatibility.'

