# spuunmux
# Autogenerated from man page /usr/share/man/man1/spuunmux.1.gz
# using Type1
complete -c spuunmux -s o --description 'base name for script and images.  Defaults to sub.'
complete -c spuunmux -s v --description 'verbosity level.  sub.  Defaults to 0.'
complete -c spuunmux -s f --description 'resize images to full size.  Defaults to 720x576.'
complete -c spuunmux -s s --description 'number of the substream to extract.  Defaults to 0.'
complete -c spuunmux -s p --description 'name of file with dvd palette.  If palette file ends with .'
complete -c spuunmux -s h --description 'print this help.'

