# sqlite
# Autogenerated from man page /usr/share/man/man1/sqlite.1.gz
# using Deroffing man parser
complete -c sqlite -o initfile --description 'Read in and process \'file\', which contains "dot commands".'
complete -c sqlite -o html --description 'Set output mode to HTML.'
complete -c sqlite -o list --description 'Set output mode to \'list\'.'
complete -c sqlite -o line --description 'Set output mode to \'line\'.'
complete -c sqlite -o column --description 'Set output mode to \'column\'.'
complete -c sqlite -o separator --description 'Specify which output field separator for \'list\' mode to use.'
complete -c sqlite -o nullvalue --description 'When a null is encountered, print \'string\'.'
complete -c sqlite -o '[no]header' --description 'Turn headers on or off.  Default is off.'
complete -c sqlite -o init --description 'Read in and process \'file\', which contains "dot commands".'
complete -c sqlite -o echo --description 'Print commands before execution.'

