# srcredact
# Autogenerated from man page /usr/share/man/man1/srcredact.1.gz
# using Type1
complete -c srcredact -s c --description 'Use the given pattern for comment lines to sear… [See Man Page]'
complete -c srcredact -s d --description 'Debug mode on.'
complete -c srcredact -s e --description 'Extract the contents for the current audience i… [See Man Page]'
complete -c srcredact -s h --description 'Print help information and exit.'
complete -c srcredact -s l --description 'List all audiences set in the file (one per line) and exit.'
complete -c srcredact -s u --description 'Take a edited file intended for the audience (t… [See Man Page]'
complete -c srcredact -s v --description 'Print version information and exit.'

