# ssh_able
# Autogenerated from man page /usr/share/man/man8/ssh_able.8
# using Deroffing man parser
complete -c ssh_able -s t -l timeout --description 'sets the time in seconds that ssh_able will wai… [See Man Page]'
complete -c ssh_able -s l -l user --description 'sets the user name to use when making a connection.'
complete -c ssh_able -s H -l help --description 'Prints this help message.'
complete -c ssh_able -s V -l version --description 'Prints the version number of this program.'

