# statd
# Autogenerated from man page /usr/share/man/man8/statd.8.gz
# using Deroffing man parser
complete -c statd -s d -l no-syslog --description 'Causes  rpc.'
complete -c statd -s F -l foreground --description 'Keeps  rpc.'
complete -c statd -s h -s '?' -l help --description 'Causes  rpc.'
complete -c statd -s H -l ha-callout --description 'Specifies a high availability callout program.'
complete -c statd -s L -l no-notify --description 'Prevents  rpc.'
complete -c statd -s n -l name --description 'Specifies the bind address used for RPC listener sockets.'
complete -c statd -s N --description 'Causes  rpc.'
complete -c statd -s o -l outgoing-port --description 'Specifies the source port number the  sm-notify… [See Man Page]'
complete -c statd -s p -l port --description 'Specifies the port number used for RPC listener sockets.'
complete -c statd -s P -l state-directory-path --description 'Specifies the pathname of the parent directory … [See Man Page]'
complete -c statd -s v -s V -l version --description 'Causes rpc.'

