# sundials-config
# Autogenerated from man page /usr/share/man/man1/sundials-config.1.gz
# using Deroffing man parser
complete -c sundials-config -s m --description 'Select the SUNDIALS module.'
complete -c sundials-config -s t --description 'Use serial of parallel vectors.'
complete -c sundials-config -s l --description 'Use C or Fortran.'
complete -c sundials-config -s s --description 'Show linking flags or C preprocessor flags (sho… [See Man Page]'
complete -c sundials-config -s h --description 'Get usage and options information.'
complete -c sundials-config -s v --description 'View the script NOTES.'
complete -c sundials-config -o lf --description 'is not valid for.'

