# svcgssd
# Autogenerated from man page /usr/share/man/man8/svcgssd.8.gz
# using Deroffing man parser
complete -c svcgssd -s f --description 'Runs  rpc.'
complete -c svcgssd -s v --description 'Increases the verbosity of the output (can be s… [See Man Page]'
complete -c svcgssd -s r --description 'If the rpcsec_gss library supports setting debu… [See Man Page]'
complete -c svcgssd -s i --description 'If the nfsidmap library supports setting debug … [See Man Page]'
complete -c svcgssd -s p --description 'Use principal instead of the default . RI nfs/ FQDN @ REALM .'
complete -c svcgssd -s n --description 'Use the system default credentials (host/ FQDN … [See Man Page]'

