# svgpp
# Autogenerated from man page /usr/share/man/man1/svgpp.1.gz
# using Deroffing man parser
complete -c svgpp -o xml-decl --description 'The value to set to the XML declaraction.'
complete -c svgpp -o system-id --description 'The value to set to the system ID of the doctype.'
complete -c svgpp -o tab-width --description 'Sets the tabulation width.  The default is 4.'
complete -c svgpp -o doc-width --description 'Sets the document preferred number of columns.'
complete -c svgpp -o no-format --description 'Disables any formatting.'
complete -c svgpp -o public-id --description 'The value to set to the public ID of the doctype.'
complete -c svgpp -o newline --description 'Specifies the type of newline to output.'
complete -c svgpp -o doctype --description 'Removes or changes the DOCTYPE declaration.'

