# telnet
# Autogenerated from man page /usr/local/share/man/man1/telnet.1
complete -c telnet -s F --description 'If Kerberos V5 authentication is being used, the F option allows the local cr…'
complete -c telnet -s N --description 'Prevents IP address to name lookup when destination host is given as an IP ad…'
complete -c telnet -s S --description 'Sets the IP type-of-service (TOS) option for the telnet connection to the val…'
complete -c telnet -s X --description 'Disables the atype type of authentication.'
complete -c telnet -s f --description 'If Kerberos V5 authentication is being used, the f option allows the local cr…'
complete -c telnet -s k --description 'If Kerberos authentication is being used, the k option requests that telnet o…'
complete -c telnet -s s --description 'Set the source IP address for the telnet connection to src_addr, which can be…'
complete -c telnet -s u --description 'Forces telnet to use AF_UNIX addresses only (e. g.'
complete -c telnet -s x --description 'Turns on encryption of the data stream if possible.'
complete -c telnet -s y --description 'Suppresses encryption of the data stream.'

