# templateCat
# Autogenerated from man page /usr/share/man/man8/templateCat.8
# using Deroffing man parser
complete -c templateCat -s H -l help --description 'prints this help page.'
complete -c templateCat -s V -l version --description 'prints the version information for this program.'
complete -c templateCat -s c -l check --description 'forces the check that confirms that the databas… [See Man Page]'

