# templateMgr
# Autogenerated from man page /usr/share/man/man8/templateMgr.8
# using Deroffing man parser
complete -c templateMgr -s H -l help --description 'Prints this help page.'
complete -c templateMgr -s V -l version --description 'Prints the version information for this program.'
complete -c templateMgr -s c -l check --description 'forces the check that confirms that the databas… [See Man Page]'

