# tesseract
# Autogenerated from man page /usr/share/man/man1/tesseract.1.gz
# using Deroffing man parser
complete -c tesseract -l tessdata-dir --description 'Specify the location of tessdata path.'
complete -c tesseract -l user-words --description 'Specify the location of user words file.'
complete -c tesseract -l user-patterns --description 'The location of user patterns file.'
complete -c tesseract -s c --description 'Set value for control parameter.'
complete -c tesseract -s l --description 'The language to use.  If none is specified, English is assumed.'
complete -c tesseract -o psm --description 'Set Tesseract to only run a subset of layout an… [See Man Page]'
complete -c tesseract -s v --description '.'
complete -c tesseract -l list-langs --description '.'
complete -c tesseract -l print-parameters --description '.'

