# tex2mail
# Autogenerated from man page /usr/share/man/man1/tex2mail.1.gz
# using Deroffing man parser
complete -c tex2mail -o linelength --description 'Wrap text at this column.'
complete -c tex2mail -o maxdef --description 'definition loops: croak if more than maxdef sub… [See Man Page]'
complete -c tex2mail -o debug --description 'output debugging messages.'
complete -c tex2mail -o by_par --description 'Expect each paragraph to be terminated by *exac… [See Man Page]'
complete -c tex2mail -o TeX --description 'Assume input formulae are in plain TeX format.'
complete -c tex2mail -o ragged --description 'leave right ragged.'
complete -c tex2mail -o noindent --description 'assume \\noindent everywhere.'

