# texconfig
# Autogenerated from man page /Library/TeX/texbin/man/man1/texconfig.1
complete -c texconfig -s P --description 'option is given.'
complete -c texconfig -s O --description 'option in dvips(1).'

