# texstudio
# Autogenerated from man page /usr/share/man/man1/texstudio.1.gz
# using Deroffing man parser
complete -c texstudio -l line --description 'After opening a file, the cursor will be placed… [See Man Page]'
complete -c texstudio -l master --description 'The file will be defined as the master document.'
complete -c texstudio -l page --description 'This option can only be used in combination wit… [See Man Page]'
complete -c texstudio -l pdf-viewer-only --description 'TeXstudio will open as a standalone pdf viewer without editor.'
complete -c texstudio -l start-always --description 'If this option is provided texstudio starts a n… [See Man Page]'
complete -c texstudio -l insert-cite --description 'Inserts the bibtex key citation at the current … [See Man Page]'

