# thumbnailer-admin
# Autogenerated from man page /usr/share/man/man1/thumbnailer-admin.1.gz
# using Deroffing man parser
complete -c thumbnailer-admin -l size --description 'a square bounding box of the specified size, fo… [See Man Page]'
complete -c thumbnailer-admin -l help --description '.'
complete -c thumbnailer-admin -s h --description '.'
complete -c thumbnailer-admin -l verbose --description '.'
complete -c thumbnailer-admin -s v --description '.'
complete -c thumbnailer-admin -l s --description '.'

