# transfig
# Autogenerated from man page /usr/share/man/man1/transfig.1.gz
# using Deroffing man parser
complete -c transfig -s m --description 'set the magnification at which the figure is re… [See Man Page]'
complete -c transfig -s f --description 'set the default font family used for text objec… [See Man Page]'
complete -c transfig -s s --description 'set the default font size (in points) for text … [See Man Page]'
complete -c transfig -s M -s T --description 'The default names are "Makefile" and "transfig.'
complete -c transfig -s o --description 'pass the specified option string through to fig2dev.'

