# ttf2svg
# Autogenerated from man page /usr/share/man/man1/ttf2svg.1.gz
# using Deroffing man parser
complete -c ttf2svg -s l -s h --description 'specifies the range of characters (by codepoint… [See Man Page]'
complete -c ttf2svg -o ascii --description 'forces usage of the ASCII character map in the … [See Man Page]'
complete -c ttf2svg -o id --description 'specifies the value for the id attribute of the… [See Man Page]'
complete -c ttf2svg -s o --description 'specifies the pathname of the output SVG docume… [See Man Page]'
complete -c ttf2svg -o testcard --description 'specifies that a sequence of SVG text elements … [See Man Page]'

