# turbostat
# Autogenerated from man page /usr/share/man/man8/turbostat.8.gz
# using Deroffing man parser
complete -c turbostat -l Counter --description '.'
complete -c turbostat -l counter --description '.'
complete -c turbostat -l Dump --description '.'
complete -c turbostat -l debug --description 'more than once may also enable internal turbost… [See Man Page]'
complete -c turbostat -l interval --description '.'
complete -c turbostat -l out --description 'The file is truncated if it already exists, and… [See Man Page]'
complete -c turbostat -l help --description '.'
complete -c turbostat -l Joules --description '.'
complete -c turbostat -l MSR --description '.'
complete -c turbostat -l msr --description '.'
complete -c turbostat -l Package --description '.'
complete -c turbostat -l processor --description '.'
complete -c turbostat -l Summary --description '.'
complete -c turbostat -l TCC --description '.'
complete -c turbostat -l version --description '.'

