# ufl-convert
# Autogenerated from man page /usr/share/man/man1/ufl-convert.1.gz
# using Deroffing man parser
complete -c ufl-convert -s h -l help --description 'Display help text and exit.'
complete -c ufl-convert -s o -l outputdir --description 'Output directory.'
complete -c ufl-convert -s i -l inputdir --description 'Output directory.'
complete -c ufl-convert -s c -l compile --description '\'Compile\' forms: apply expression transformatio… [See Man Page]'
complete -c ufl-convert -s f -l format --description 'Rendering format (str, repr, tree, dot, latex).'
complete -c ufl-convert -s t -l filetype --description 'Output file type (txt, py, dot, tex, ps, pdf, png).'
complete -c ufl-convert -s s -l show --description 'Open in an external viewer.'

