# ufl-analyse
# Autogenerated from man page /usr/share/man/man1/ufl-analyse.1.gz
# using Deroffing man parser
complete -c ufl-analyse -s h -l help --description 'Display help text and exit.'
complete -c ufl-analyse -s q -l quiet --description 'Do not print form information to screen.'
complete -c ufl-analyse -s w -l write --description 'Write form information to file.'

