# unity
# Autogenerated from man page /usr/share/man/man1/unity.1.gz
# using Deroffing man parser
complete -c unity -l advanced-debug --description 'Runs unity under debugging (using gdb or anothe… [See Man Page]'
complete -c unity -l compiz-path --description 'Runs the compositor from a non-standard location.'
complete -c unity -l debug --description 'Runs Unity under  gdb and prints a stack trace on crash.'
complete -c unity -s h -l help --description 'Prints a usage message and exits.'
complete -c unity -l log --description 'This parameter, followed by a path or filename,… [See Man Page]'
complete -c unity -l replace --description 'Deprecated option for backwards compatibility.   Has no effect.'
complete -c unity -l reset-icons --description 'Resets the default Launcher icons.'
complete -c unity -s v -l version --description 'Shows the program version number and exits.'
complete -c unity -l verbose --description '.'

