# unity-greeter
# Autogenerated from man page /usr/share/man/man1/unity-greeter.1.gz
# using Deroffing man parser
complete -c unity-greeter -s v -l version --description 'Show release version.'
complete -c unity-greeter -l test-mode --description 'Run the greeter in a test mode inside the current X session.'
complete -c unity-greeter -s '?' -l help --description 'Show help options.  SEE ALSO lightdm.'

