# unity-tweak-tool
# Autogenerated from man page /usr/share/man/man1/unity-tweak-tool.1.gz
# using Deroffing man parser
complete -c unity-tweak-tool -s u --description 'Starts unity-tweak-tool in Unity section.'
complete -c unity-tweak-tool -s w --description 'Starts unity-tweak-tool in Window Manager section.'
complete -c unity-tweak-tool -s a --description 'Starts unity-tweak-tool in Appearance section.'
complete -c unity-tweak-tool -s s --description 'Starts unity-tweak-tool in System section.'
complete -c unity-tweak-tool -l reset-unity --description 'Reset Unity, wiping all changes to configuration.'

