# update-fmtutil
# Autogenerated from man page /usr/share/man/man8/update-fmtutil.8.gz
# using Darwin man parser
complete -c update-fmtutil -l check --description 'Executes additional checks that all necessary f… [See Man Page]'
complete -c update-fmtutil -l quiet --description 'don\'t write anything to the standard output dur… [See Man Page]'
complete -c update-fmtutil -l help --description 'print a summary of the command-line usage of up… [See Man Page]'
complete -c update-fmtutil -l version --description 'output version information and exit El Pp Note … [See Man Page]'

