# update-language
# Autogenerated from man page /usr/share/man/man8/update-language.8.gz
# using Deroffing man parser
complete -c update-language -s c -l conf-file --description 'file giving additional hyphen specifications .'
complete -c update-language -s d -l output-dir --description 'directory where files are written.'
complete -c update-language -l checks --description 'perform sanity checks on the generated config file.'
complete -c update-language -s q -l quiet --description 'don\'t write anything to the standard output dur… [See Man Page]'
complete -c update-language -s h -s '?' -l help --description 'display this help message and exit.'
complete -c update-language -s o -l output-file --description '.'
complete -c update-language -l version --description 'output version information and exit FILES The d… [See Man Page]'

