# update-leap
# Autogenerated from man page /usr/share/man/man1/update-leap.1.gz
# using Deroffing man parser
complete -c update-leap -s c --description 'functions, e. g.  to copy the file to other local systems.'

