# update-usbids
# Autogenerated from man page /usr/share/man/man8/update-usbids.8.gz
# using Deroffing man parser
complete -c update-usbids -s q --description 'Be quiet and do not report anything except errors.'

