# update_fstab
# Autogenerated from man page /usr/share/man/man8/update_fstab.8
# using Deroffing man parser
complete -c update_fstab -s H -l help --description 'Prints this help page.'
complete -c update_fstab -s V -l version --description 'Prints version information about this program.  FILES.'

