# vcd2vzt
# Autogenerated from man page /usr/share/man/man1/vcd2vzt.1.gz
# using Type1
complete -c vcd2vzt -s v -l vcdname --description 'Specify VCD input filename.'
complete -c vcd2vzt -s l -l vztname --description 'Specify VZT output filename.'
complete -c vcd2vzt -s d -l depth --description 'Specify 0. 9 gzip compression depth, default is 4.'
complete -c vcd2vzt -s m -l maxgranule --description 'Specify number of granules per section, default is 8.'
complete -c vcd2vzt -s b -l break --description 'Specify break size (default = 0 = off).'
complete -c vcd2vzt -s z -l ziptype --description 'Specify zip type (default = 0 gzip, 1 = bzip2, 2 = lzma).'
complete -c vcd2vzt -s t -l twostate --description 'Forces MVL2 twostate mode (default is MVL4).'
complete -c vcd2vzt -s r -l rle --description 'Uses an bitwise RLE compression on the value table.'
complete -c vcd2vzt -s h -l help --description 'Show help screen.'

