# vcd2lxt
# Autogenerated from man page /usr/share/man/man1/vcd2lxt.1.gz
# using Type1
complete -c vcd2lxt -o stats --description 'Prints out statistics on all nets in VCD file i… [See Man Page]'
complete -c vcd2lxt -o clockpack --description 'Apply two-way subtraction algorithm in order to… [See Man Page]'
complete -c vcd2lxt -o chgpack --description 'Emit data to file after being filtered through zlib (gzip).'
complete -c vcd2lxt -o linear --description 'Write out LXT in "linear" format with no backpointers.'

