# vcd2lxt2
# Autogenerated from man page /usr/share/man/man1/vcd2lxt2.1.gz
# using Type1
complete -c vcd2lxt2 -s v -l vcdname --description 'Specify VCD input filename.'
complete -c vcd2lxt2 -s l -l lxtname --description 'Specify LXT2 output filename.'
complete -c vcd2lxt2 -s d -l depth --description 'Specify 0. 9 gzip compression depth, default is 4.'
complete -c vcd2lxt2 -s m -l maxgranule --description 'Specify number of granules per section, default is 8.'
complete -c vcd2lxt2 -s b -l break --description 'Specify break size (default = 0 = off).'
complete -c vcd2lxt2 -s p -l partialmode --description 'Specify partial zip mode 0 = monolithic, 1 = separation.'
complete -c vcd2lxt2 -s c -l checkpoint --description 'Specify checkpoint mode.'
complete -c vcd2lxt2 -s h -l help --description 'Show help screen.'

