# vcd2fst
# Autogenerated from man page /usr/share/man/man1/vcd2fst.1.gz
# using Type1
complete -c vcd2fst -s v -l vcdname --description 'Specify VCD/FSDB/VPD/WLF input filename.'
complete -c vcd2fst -s f -l fstname --description 'Specify FST output filename.'
complete -c vcd2fst -s 4 -l fourpack --description 'Indicates that LZ4 should be used for value cha… [See Man Page]'
complete -c vcd2fst -s F -l fastpack --description 'Indicates that fastlz should be used instead of… [See Man Page]'
complete -c vcd2fst -l zlibpack --description 'Indicates that zlib should be used instead of L… [See Man Page]'
complete -c vcd2fst -s c -l compress --description 'Indicates that the entire file should be run th… [See Man Page]'
complete -c vcd2fst -s p -l parallel --description 'Indicates that parallel mode should be enabled.'
complete -c vcd2fst -s h -l help --description 'Show help screen.'

