# vcdimager
# Autogenerated from man page /usr/share/man/man1/vcdimager.1.gz
# using Deroffing man parser
complete -c vcdimager -s t -l type --description 'select VideoCD type (\'vcd11\', \'vcd2\', \'svcd\' or… [See Man Page]'
complete -c vcdimager -s c -l cue-file --description 'specify cue file for output (default: \'videocd. cue\').'
complete -c vcdimager -s b -l bin-file --description 'specify bin file for output (default: \'videocd. bin\').'
complete -c vcdimager -s l -l iso-volume-label --description 'specify ISO volume label for video cd (default: \'VIDEOCD\').'
complete -c vcdimager -l iso-application-id --description 'specify ISO application id for video cd (default: \'\').'
complete -c vcdimager -l info-album-id --description 'specify album id for video cd set (default: \'\').'
complete -c vcdimager -l volume-count --description 'specify number of volumes in album set.'
complete -c vcdimager -l volume-number --description 'specify album set sequence number (< volume-count).'
complete -c vcdimager -l broken-svcd-mode --description 'enable non-compliant compatibility mode for broken devices.'
complete -c vcdimager -l update-scan-offsets --description 'update scan data offsets in video mpeg2 stream.'
complete -c vcdimager -l sector-2336 --description 'use 2336 byte sectors for output.'
complete -c vcdimager -l add-dir --description 'add empty dir to ISO fs.'
complete -c vcdimager -l add-file --description 'add single file to ISO fs.'
complete -c vcdimager -l add-file-2336 --description 'add file containing full 2336 byte sectors to ISO fs.'
complete -c vcdimager -s T -l create-time --description 'specify creation date on files in CD image (def… [See Man Page]'
complete -c vcdimager -s v -l verbose --description 'be verbose.'
complete -c vcdimager -s q -l quiet --description 'show only critical messages.'
complete -c vcdimager -s V -l version --description 'display version and copyright information and exit .'
complete -c vcdimager -s '?' -l help --description 'Show this help message.'
complete -c vcdimager -l usage --description 'Display brief usage message AUTHOR Written by H… [See Man Page]'

