# vcdxbuild
# Autogenerated from man page /usr/share/man/man1/vcdxbuild.1.gz
# using Deroffing man parser
complete -c vcdxbuild -s i -l image-type --description 'specify image type for output (default: \'bincue\').'
complete -c vcdxbuild -s o -l image-option --description 'specify image option.'
complete -c vcdxbuild -s c -l cue-file --description 'specify cue file for output (default: \'videocd. cue\').'
complete -c vcdxbuild -s b -l bin-file --description 'specify bin file for output (default: \'videocd. bin\').'
complete -c vcdxbuild -l cdrdao-file --description 'specify cdrdao-style image filename base.'
complete -c vcdxbuild -l sector-2336 --description 'use 2336 byte sectors for output.'
complete -c vcdxbuild -s T -l create-time --description 'specify creation date on files in CD image (def… [See Man Page]'
complete -c vcdxbuild -s p -l progress --description 'show progress.'
complete -c vcdxbuild -l dump-dtd --description 'dump internal DTD to stdout.'
complete -c vcdxbuild -l filename-encoding --description 'use given charset encoding for filenames instead of UTF8.'
complete -c vcdxbuild -s v -l verbose --description 'be verbose.'
complete -c vcdxbuild -s q -l quiet --description 'show only critical messages.'
complete -c vcdxbuild -l gui --description 'enable GUI mode.'
complete -c vcdxbuild -s V -l version --description 'display version and copyright information and exit .'
complete -c vcdxbuild -s '?' -l help --description 'Show this help message.'
complete -c vcdxbuild -l usage --description 'Display brief usage message AUTHOR Written by H… [See Man Page]'

