# vcdxgen
# Autogenerated from man page /usr/share/man/man1/vcdxgen.1.gz
# using Deroffing man parser
complete -c vcdxgen -s o -l output-file --description 'specify xml file for output (default: \'videocd. xml\').'
complete -c vcdxgen -s t -l type --description 'select VideoCD type (\'vcd11\', \'vcd2\', \'svcd\' or… [See Man Page]'
complete -c vcdxgen -s l -l iso-volume-label --description 'specify ISO volume label for video cd (default: \'VIDEOCD\').'
complete -c vcdxgen -l iso-application-id --description 'specify ISO application id for video cd (default: \'\').'
complete -c vcdxgen -l info-album-id --description 'specify album id for video cd set (default: \'\').'
complete -c vcdxgen -l volume-count --description 'specify number of volumes in album set.'
complete -c vcdxgen -l volume-number --description 'specify album set sequence number (< volume-count).'
complete -c vcdxgen -l broken-svcd-mode --description 'enable non-compliant compatibility mode for broken devices.'
complete -c vcdxgen -l update-scan-offsets --description 'update scan data offsets in video mpeg2 stream.'
complete -c vcdxgen -l nopbc --description 'don\'t create PBC.'
complete -c vcdxgen -l add-dirtree --description 'add directory contents recursively to ISO fs root.'
complete -c vcdxgen -l add-dir --description 'add empty dir to ISO fs.'
complete -c vcdxgen -l add-file --description 'add single file to ISO fs.'
complete -c vcdxgen -l add-file-2336 --description 'add file containing full 2336 byte sectors to ISO fs.'
complete -c vcdxgen -l filename-encoding --description 'use given charset encoding for filenames instead of UTF8.'
complete -c vcdxgen -s v -l verbose --description 'be verbose.'
complete -c vcdxgen -s q -l quiet --description 'show only critical messages.'
complete -c vcdxgen -s V -l version --description 'display version and copyright information and exit .'
complete -c vcdxgen -s '?' -l help --description 'Show this help message.'
complete -c vcdxgen -l usage --description 'Display brief usage message AUTHOR Written by H… [See Man Page]'

