# vcdxminfo
# Autogenerated from man page /usr/share/man/man1/vcdxminfo.1.gz
# using Deroffing man parser
complete -c vcdxminfo -s i -l generic-info --description 'show generic information.'
complete -c vcdxminfo -s a -l dump-aps --description 'dump APS data.'
complete -c vcdxminfo -l relaxed-aps --description 'relax APS constraints.'
complete -c vcdxminfo -s o -l output-file --description 'file for XML output.'
complete -c vcdxminfo -s p -l progress --description 'show progress.'
complete -c vcdxminfo -s v -l verbose --description 'be verbose.'
complete -c vcdxminfo -s q -l quiet --description 'show only critical messages.'
complete -c vcdxminfo -l gui --description 'enable GUI mode.'
complete -c vcdxminfo -s V -l version --description 'display version and copyright information and exit .'
complete -c vcdxminfo -s '?' -l help --description 'Show this help message.'
complete -c vcdxminfo -l usage --description 'Display brief usage message AUTHOR Written by H… [See Man Page]'

