# verify_mounts
# Autogenerated from man page /usr/share/man/man8/verify_mounts.8
# using Deroffing man parser
complete -c verify_mounts -s H -l help --description 'Prints this man page.'
complete -c verify_mounts -s V -l version --description 'Prints version information.  FILES.'

