# vermin
# Autogenerated from man page /usr/share/man/man1/vermin.1.gz
# using Type1
complete -c vermin -o 'h[elp]' --description 'Prints out help screen.'
complete -c vermin -o emitmono --description 'Emit monolithic (parser view of) file to fname.'
complete -c vermin -o emitstems --description 'Emit source code stems to stdout.'
complete -c vermin -o emitvars --description 'Emit source code variables to stdout.'
complete -c vermin -o Dx --description 'Equivalent to `define X Y in source.'
complete -c vermin -o pragma --description 'Add name (synopsys, verilint, vertex) to accepted pragmas.'
complete -c vermin -s y --description 'Add directory dirname to source input path.'
complete -c vermin -o yi --description 'Add directory dirname to source input path (cas… [See Man Page]'

