# veusz
# Autogenerated from man page /usr/share/man/man1/veusz.1.gz
# using Type1
complete -c veusz -l unsafe-mode --description 'Do not check opened scripts for the presence of… [See Man Page]'
complete -c veusz -l listen --description 'Read Veusz commands from stdin, executing them,… [See Man Page]'
complete -c veusz -l quiet --description 'If in listening mode, do not open a window befo… [See Man Page]'
complete -c veusz -l export --description 'Export the next Veusz document file on the comm… [See Man Page]'
complete -c veusz -l plugin --description 'Loads the Veusz plugin \\s-1FILE\\s0 when starting Veusz.'
complete -c veusz -l help --description 'Displays the options to the program and exits.'

