# vzt2vcd
# Autogenerated from man page /usr/share/man/man1/vzt2vcd.1.gz
# using Type1
complete -c vzt2vcd -s v -l vztname --description 'Specify VZT input filename.'
complete -c vzt2vcd -s o -l output --description 'Specify optional VCD output filename.'
complete -c vzt2vcd -s f -l flatearth --description 'Emit flattened hierarchies.'
complete -c vzt2vcd -s c -l coalesce --description 'Coalesce bitblasted vectors.'
complete -c vzt2vcd -s n -l notruncate --description 'Do not shorten bitvectors.'

