# vztminer
# Autogenerated from man page /usr/share/man/man1/vztminer.1.gz
# using Type1
complete -c vztminer -s d -l dumpfile --description 'Specify VZT input dumpfile.'
complete -c vztminer -s m -l match --description 'Specifies "bitwise" match data (binary, real, string).'
complete -c vztminer -s x -l hex --description 'Specifies hexadecimal match data that will auto… [See Man Page]'
complete -c vztminer -s n -l namesonly --description 'Indicates that only facnames should be printed … [See Man Page]'
complete -c vztminer -s c -l comprehensive --description 'Indicates that results are not to stop after the first match.'

