# wordlist2dawg
# Autogenerated from man page /usr/share/man/man1/wordlist2dawg.1.gz
# using Deroffing man parser
complete -c wordlist2dawg -s t --description '.'
complete -c wordlist2dawg -s r --description '.'
complete -c wordlist2dawg -s l --description 'ARGUMENTS.'

