# x-terminal-emulator
# Autogenerated from man page /usr/share/man/man1/x-terminal-emulator.1.gz
# using Type1
complete -c x-terminal-emulator -s e -l command --description 'Execute the argument to this option inside the terminal.'
complete -c x-terminal-emulator -s x -l execute --description 'Execute the remainder of the command line inside the terminal.'
complete -c x-terminal-emulator -l window-with-profile --description 'Open a new window containing a tab with the given profile.'
complete -c x-terminal-emulator -l tab-with-profile --description 'Open a tab in the window with the given profile.'
complete -c x-terminal-emulator -l window-with-profile-internal-id --description 'Open a new window containing a tab with the given profile  ID.'
complete -c x-terminal-emulator -l tab-with-profile-internal-id --description 'Open a tab in the window with the given profile ID.'
complete -c x-terminal-emulator -l role --description 'Set the role for the last-specified window; app… [See Man Page]'
complete -c x-terminal-emulator -l show-menubar --description 'Turn on the menu bar for the last-specified win… [See Man Page]'
complete -c x-terminal-emulator -l hide-menubar --description 'Turn off the menu bar for the last-specified wi… [See Man Page]'
complete -c x-terminal-emulator -l geometry --description 'X geometry specification (see "X" man page), ca… [See Man Page]'
complete -c x-terminal-emulator -l working-directory --description 'Set the terminal\'s working directory to DIRNAME.'

