# xfig
# Autogenerated from man page /usr/share/man/man1/xfig.1.gz
# using Deroffing man parser
complete -c xfig -o help --description '.'
complete -c xfig -s a --description '.'
complete -c xfig -o bal --description 'msec.'
complete -c xfig -o bol --description 'font.'
complete -c xfig -o butt --description 'font.'
complete -c xfig -o but_ --description 'number.'
complete -c xfig -o pheight --description 'parameter to reduce the canvas height for small screens.'
complete -c xfig -o cbg --description '.'
complete -c xfig -o bg --description 'option.'
complete -c xfig -o center --description '.'
complete -c xfig -o centim --description '.'
complete -c xfig -o 'metric.' --description '.'
complete -c xfig -o cfg --description '.'
complete -c xfig -o fg --description 'option.'
complete -c xfig -o correct_font_size --description '.'
complete -c xfig -s F --description 'option to make it use points (1/72 inch).'
complete -c xfig -o deb --description '.'
complete -c xfig -o dep --description '.'
complete -c xfig -o visual --description 'option.'
complete -c xfig -o donta --description '.'
complete -c xfig -o dontshowb --description '.'
complete -c xfig -o 'showballoons.' --description '.'
complete -c xfig -o dontshowl --description '.'
complete -c xfig -o dontshowz --description '.'
complete -c xfig -o dontsw --description '.'
complete -c xfig -o 'max_image_colors.' --description '.'
complete -c xfig -o enc --description 'encoding.'
complete -c xfig -o exportL --description 'language.'
complete -c xfig -o export_m --description 'width.'
complete -c xfig -o fli --description '.'
complete -c xfig -o flu --description '.'
complete -c xfig -o free --description 'resolution.'
complete -c xfig -o geom --description '[ WxH ] [+X+Y].'
complete -c xfig -o pwidth --description 'and/or .'
complete -c xfig -o but_per_row --description 'option to  tell xfig to put 3 or 4 buttons per… [See Man Page]'
complete -c xfig -o gh --description 'postscript-interpreter.'
complete -c xfig -o grid_c --description 'color.'
complete -c xfig -o grid_u --description 'unit.'
complete -c xfig -o hidd --description '.'
complete -c xfig -o dontshowd --description '.'
complete -c xfig -o icon_ --description '.'
complete -c xfig -o 'list_view.' --description '.'
complete -c xfig -o iconG --description '+ X + Y.'
complete -c xfig -o im --description 'editor.'
complete -c xfig -o inc --description '(or -imperial).'
complete -c xfig -o ins --description '.'
complete -c xfig -o internalBW --description '.'
complete -c xfig -o international --description '.'
complete -c xfig -o jpeg --description 'quality.'
complete -c xfig -s k --description 'compose-key-file.'
complete -c xfig -o lan --description '.'
complete -c xfig -o lat --description '.'
complete -c xfig -o le --description '.'
complete -c xfig -o library_d --description 'directory.'
complete -c xfig -o library_i --description 'size.'
complete -c xfig -o lis --description '.'
complete -c xfig -o 'icon_view.' --description '.'
complete -c xfig -o mag --description 'mag.'
complete -c xfig -o max --description 'numcols.'
complete -c xfig -o me --description '.'
complete -c xfig -o centimeters --description 'may also be used.'
complete -c xfig -o mo --description '.'
complete -c xfig -o mu --description '.'
complete -c xfig -o 'single.' --description '.'
complete -c xfig -o noo --description '.'
complete -c xfig -o 'overlap.' --description '.'
complete -c xfig -o nor --description 'font.'
complete -c xfig -o nosc --description '.'
complete -c xfig -o nosp --description '.'
complete -c xfig -o splash --description ').'
complete -c xfig -o not --description '.'
complete -c xfig -o nowrite_bak --description '.'
complete -c xfig -o ov --description '.'
complete -c xfig -o 'nooverlap.' --description '.'
complete -c xfig -o pag --description 'color.'
complete -c xfig -o showpageborder --description 'option (resource Fig.'
complete -c xfig -o pap --description 'size.'
complete -c xfig -o ph --description 'height.'
complete -c xfig -o metric --description 'setting).'
complete -c xfig -o po --description '.'
complete -c xfig -o pw --description 'width.'
complete -c xfig -o righ --description '.'
complete -c xfig -o rigi --description '.'
complete -c xfig -o ru --description '.'
complete -c xfig -o scala --description '.'
complete -c xfig -o scale_factor --description 'scale.'
complete -c xfig -o update --description 'option to do batch scaling of figures.'
complete -c xfig -o showa --description '.'
complete -c xfig -o showallbuttons --description 'option makes all of the indicator buttons visi… [See Man Page]'
complete -c xfig -o showb --description '.'
complete -c xfig -o dontshowballoons --description '.'
complete -c xfig -o showd --description '.'
complete -c xfig -o showl --description '.'
complete -c xfig -o shown --description '.'
complete -c xfig -o showp --description '.'
complete -c xfig -o pageborder --description 'option (default: light blue).'
complete -c xfig -o showz --description '.'
complete -c xfig -o si --description '.'
complete -c xfig -o 'multiple.' --description '.'
complete -c xfig -o sm --description 'factor.'
complete -c xfig -o spec --description '.'
complete -c xfig -o spel --description 'command.'
complete -c xfig -o spinner_d --description 'msec.'
complete -c xfig -o spinner_r --description 'msec.'
complete -c xfig -o startfi --description 'stylenumber.'
complete -c xfig -o startfo --description 'pointsize.'
complete -c xfig -o startg --description 'modenumber.'
complete -c xfig -o startla --description 'font.'
complete -c xfig -o startli --description 'width.'
complete -c xfig -o startpo --description 'modenumber.'
complete -c xfig -o startp --description 'font.'
complete -c xfig -o startt --description 'stepsize.'
complete -c xfig -o ta --description '.'
complete -c xfig -o track --description '.'
complete -c xfig -o tran --description 'color_number.'
complete -c xfig -o users --description 'scale.'
complete -c xfig -o useru --description 'units.'
complete -c xfig -o depth --description 'option.'
complete -c xfig -o write_bak --description '.'
complete -c xfig -o zoom --description 'zoomscale.'

