# xosview
# Autogenerated from man page /usr/share/man/man1/xosview.1.gz
# using Deroffing man parser
complete -c xosview -s v --description '.'
complete -c xosview -o name --description '.'
complete -c xosview -o display --description '.'
complete -c xosview -o font --description '.'
complete -c xosview -o title --description '.'
complete -c xosview -o geometry --description '.'
complete -c xosview -o cpus --description '.'
complete -c xosview -o network --description '.'
complete -c xosview -o networkBW --description '.'
complete -c xosview -o networkBandwidth --description '.'
complete -c xosview -o pagespeed --description '.'
complete -c xosview -o ints --description '.'
complete -c xosview -o interrupts --description '.'
complete -c xosview -o intrate --description '.'
complete -c xosview -o xrm --description '.'

