#!/usr/bin/env sh

USAGE="Usage: $0 [-n num-results] [-e] port-name"
OPTIND=1
EXACT=0
n=0

: ${PORTSDIR:="/usr/ports"}

EXCLUDE="distfiles"
for d in `find "${PORTSDIR}" -type d \
                -mindepth 1 -maxdepth 1 \
                -regex "${PORTSDIR}/[A-Z].*" \
                | xargs basename`; do 
        EXCLUDE="${EXCLUDE}|$d"
done
echo $EXCLUDE

while getopts "en:" opt; do
	case "${opt}" in
		e)
			EXACT=1
			;;
		n)
			n=${OPTARG}
			;;
		\?)
			echo "${USAGE}"
			exit 1
			;;
	esac
done

shift $((OPTIND-1))

[ "${1:-}" = "--" ] && shift


if [ $# -le 0 ]; then
	echo "No port name given"
	echo "${USAGE}"
fi

for portname in $@
do
	if [ ${EXACT} -eq 0 ]; then
		foundports=`find -E "${PORTSDIR}" -type d -mindepth 2 -maxdepth 2 \
                        -name "*${portname}*" \! -regex "${PORTSDIR}/(${EXCLUDE})/${portname}"\
			| sed "s#^${PORTSDIR}/##"`
	else
		foundports=`find "${PORTSDIR}" -type d -mindepth 2 -maxdepth 2 \
                        -name "${portname}" ! -regex "${PORTSDIR}/(${EXCLUDE})/${portname}" \
			| sed "s#^${PORTSDIR}/##"`
	fi
	numports=`echo ${foundports} | wc -w`
	if [ $n -eq 0 ]; then
		printf "${foundports}\n"
	else
		printf "${foundports}\n" | head -n $n
	fi
done
