#!/usr/bin/env fish

# Check if VLC is running using pgrep
if pgrep -f 'VOWRAM'
	# `set' will fail if pgrep does so if there is no running 
	# process the loop never executes
	while set pids (pgrep -f 'VOWRAM')
		kill $pids
		sleep 1
	end
else
        # We don't want a GUI so tell VLC to use a dummy interface
        vlc --intf dummy 'vcd://' 'http://18853.live.streamtheworld.com/VOWRAMAAC.aac' >/dev/null ^&1 &

        # Since the above Python script doesn't exit, it doesn't set
        # $status. Hence this script appears to fail when `prep(1)'
        # on line 4 fails. Setting the return code here isn't the most
        # elegant but it works.
        true
end
